---
title: "Comparison of Cant estimates to results of Gruber et al 2019"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r read_params_local, include = FALSE, eval=FALSE}
params_local <-
  read_rds(here::here("data/auxillary",
                       "params_local.rds"))

```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")

# path_version_data     <-
#   paste(path_observations,
#         params_local$Version_ID,
#         "/data/",
#         sep = "")
# 
# path_version_figures  <-
#   paste(path_observations,
#         params_local$Version_ID,
#         "/figures/",
#         sep = "")
```

```{r load_libraries_specific, include = FALSE}
library(scales)
library(marelac)
library(gt)
```

# Data sources

Following Cant estimates are used:

- Zonal mean (basin, lat, depth)
- Inventories (lat, lon)
## Gruber 2019

Results from Gruber et al 2019 are referred to as G19.

```{r read_Gruber_cant_file}

cant_inv_G19 <-
  read_csv(paste(path_preprocessing,
                 "G19_cant_inv.csv",
                 sep = ""))

cant_inv_G19 <- cant_inv_G19 %>%
  select(-eras)

cant_zonal_G19 <-
  read_csv(paste(path_preprocessing,
                 "G19_cant_zonal.csv",
                 sep = ""))

cant_zonal_G19 <- cant_zonal_G19 %>%
  filter(eras == "JGOFS_GO") %>%
  select(lat,
         depth,
         basin_AIP,
         cant_mean,
         cant_pos_mean,
         cant_sd,
         cant_pos_sd)


```


# Color scales G19

```{r color_test}

p_map_cant_inv(
      cant_inv_G19
)

breaks = params_global$breaks_cant_pos_inv
breaks = c(seq(0,16,1),Inf)
breaks_n <- length(breaks) - 1

cant_inv_G19 <- cant_inv_G19 %>%
  mutate(cant_pos_inv_int = cut(cant_pos_inv,
                       breaks,
                       right = FALSE))

map +
  geom_raster(data = cant_inv_G19,
              aes(lon, lat, fill = cant_pos_inv_int)) +
  scale_fill_manual(values = p_gruber_rainbow(breaks_n),
                    name = expression(atop(Delta * C["ant,pos"],
                                           (mol ~ m ^ {
                                             -2
                                           })))) +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm"))) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave(path = "output/Gruber_2019_comparison",
       filename = "G19_gruber_rainbow.png",
       height = 3,
       width = 8)

map +
  geom_raster(data = cant_inv_G19,
              aes(lon, lat, fill = cant_pos_inv_int)) +
  scale_fill_viridis_d(name = expression(atop(Delta * C["ant,pos"],
                                           (mol ~ m ^ {
                                             -2
                                           })))) +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm"))) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave(path = "output/Gruber_2019_comparison",
       filename = "G19_viridis.png",
       height = 3,
       width = 8)

map +
  geom_raster(data = cant_inv_G19,
              aes(lon, lat, fill = cant_pos_inv_int)) +
  scale_fill_scico_d(palette = "batlow",
                   name = expression(atop(Delta * C["ant,pos"],
                                           (mol ~ m ^ {
                                             -2
                                           })))) +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm"))) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave(path = "output/Gruber_2019_comparison",
       filename = "G19_batlow.png",
       height = 3,
       width = 8)


```

