```{r r join_data_and_meta_data, include=FALSE}

dcant_zonal_all <- full_join(dcant_zonal_all,
                           params_local_all)

dcant_profile_all <- full_join(dcant_profile_all,
                           params_local_all)

dcant_budget_basin_AIP_layer_all <-
  full_join(dcant_budget_basin_AIP_layer_all,
            params_local_all)

dcant_zonal_bias_all <- full_join(dcant_zonal_bias_all,
                                params_local_all)

```

# Uncertainty limit

```{r define_sd_uncertainty_limit}

sd_uncertainty_limit <- 1.5

```

# Individual cases

## Absoulte values

```{r cases_absolute, fig.asp=1.2}

dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(basin_AIP, data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant",
      plot_slabs = "n",
      subtitle_text = paste(
        "data_source: ",
        unique(.x$data_source),
        "| basin:",
        unique(.x$basin_AIP)
      )
    ) +
      facet_grid({{config}} ~ period)
  )

p_dcant_Indian_1994_2004 <-
  dcant_zonal_all %>%
  filter(data_source %in% c("obs"),
         period == "1994 - 2004",
         basin_AIP == "Indian") %>%
  p_section_zonal_continous_depth(var = "dcant",
                                  plot_slabs = "n",
                                  subtitle_text = "Indian Ocean") +
  facet_grid({{config}} ~ period)

# ggsave(plot = p_dcant_Indian_1994_2004,
#        path = "output/other",
#        filename = "zonal_indian_1994_2004.png",
#        height = 8,
#        width = 5)

p_dcant_Indian_2004_2014 <-
  dcant_zonal_all %>%
  filter(data_source %in% c("obs"),
         period == "2004 - 2014",
         basin_AIP == "Pacific") %>%
  p_section_zonal_continous_depth(var = "dcant",
                                  plot_slabs = "n",
                                  subtitle_text = "Pacific Ocean") +
  facet_grid({{config}} ~ period)

# ggsave(plot = p_dcant_Indian_2004_2014,
#        path = "output/other",
#        filename = "zonal_Pacific_2004_2014.png",
#        height = 8,
#        width = 5)

```

## Biases

```{r cases_bias, fig.asp=1.2}

dcant_zonal_bias_all %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_bias",
      col = "divergent",
      plot_slabs = "n",
      subtitle_text = paste("basin:",
        unique(.x$basin_AIP)
      )
    ) +
      facet_grid({{config}} ~ period)
  )


```


### Density distribution

```{r bias_density_distribution, fig.asp=1}

dcant_zonal_bias_all %>%
  ggplot(aes(dcant_bias, col = {{config}})) +
  scale_color_brewer(palette = "Dark2") +
  geom_vline(xintercept = 0) +
  geom_density() +
  facet_grid(period ~.) +
  coord_cartesian(xlim = c(-10, 10))

```


## Bias correlation eras

```{r cases_bias_correlation, fig.asp=1}

dcant_zonal_bias_all_corr <- dcant_zonal_bias_all %>%
  select(lat, depth, basin_AIP, dcant_bias, {{config}}, period) %>% 
  pivot_wider(names_from = period,
              values_from = dcant_bias, 
              names_prefix = "dcant_bias ")

dcant_zonal_bias_all_corr %>% 
  ggplot(aes(`dcant_bias 1994 - 2004`, `dcant_bias 2004 - 2014`)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_bin2d() +
  coord_fixed() +
  facet_grid({{config}} ~ basin_AIP) +
  scale_fill_viridis_c()

```

## Concentration profiles

### Data source

```{r profiles_per_data_source, fig.asp=1.5}

dcant_profile_all %>%
  group_split(period) %>%
  map(
    ~ ggplot(data = .x,
             aes(
               dcant, depth,
               col = data_source, fill = data_source
             )) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_ribbon(
        aes(xmin = dcant - dcant_sd,
            xmax = dcant + dcant_sd),
        alpha = 0.2,
        col = "transparent"
      ) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid({{config}} ~ basin_AIP)
  )

```

### Basin separation

```{r profiles_per_{{config}}, fig.asp=1}

dcant_profile_all %>%
  group_split(period) %>%
  map(
    ~ ggplot(data = .x,
             aes(
               dcant, depth,
               col = {{config}}, fill = {{config}}
             )) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid(data_source ~ basin_AIP)
  )

```

### Era

```{r profiles_per_period, fig.asp=0.5}

dcant_profile_all %>%
  arrange(depth) %>%
  filter(period != "1994 - 2014") %>%
  group_split(data_source) %>%
  map(
    ~ ggplot(
      data = .x,
      aes(
        dcant,
        depth,
        col = period,
        group = interaction({{config}}, period)
      )
    ) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("data_source", unique(.x$data_source))) +
      facet_grid(. ~ basin_AIP)
  )

```

## Layer budgets

```{r layer_budget_per_data_source, fig.asp=1.5}

dcant_budget_basin_AIP_layer_all %>%
  filter(estimate == "dcant") %>% 
  mutate(dcant = value,
         inv_depth = fct_inorder(as.factor(inv_depth))) %>% 
  group_split(period) %>%
  # head(1) %>% 
  map(
    ~ ggplot(data = .x,
             aes(dcant, inv_depth,
                 fill = {{config}})) +
      geom_vline(xintercept = 0) +
      geom_col(position = "dodge") +
      scale_y_discrete(limits = rev) +
      scale_fill_brewer(palette = "Dark2") +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid(data_source ~ basin_AIP)
  )

```



# Ensemble

```{r calc_ensemble_metrics}

dcant_zonal_ensemble <- dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(lat, depth, basin_AIP, data_source, period) %>%
  summarise(
    dcant_ensemble_mean = mean(dcant),
    dcant_sd = sd(dcant),
    dcant_range = max(dcant) - min(dcant)
  ) %>%
  ungroup()


dcant_budget_basin_AIP_layer_ensemble <-
  dcant_budget_basin_AIP_layer_all %>%
  mutate(inv_depth = fct_inorder(as.factor(inv_depth))) %>%
  filter(data_source %in% c("mod", "obs"),
         estimate == "dcant") %>%
  rename(dcant = value) %>%
  group_by(inv_depth, data_source, period, basin_AIP) %>%
  summarise(
    dcant_mean = mean(dcant),
    dcant_sd = sd(dcant),
    dcant_max = max(dcant),
    dcant_min = min(dcant)
  ) %>%
  ungroup()


```

## Mean

```{r ensemble_mean}

dcant_zonal_ensemble %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_ensemble_mean",
      plot_slabs = "n",
      subtitle_text = paste("basin:",
                            unique(.x$basin_AIP))
    ) +
      facet_grid(data_source ~ period)
  )


```

## Mean bias

```{r ensemble_mean_bias, fig.asp=0.5}

dcant_zonal_ensemble_bias <- full_join(
  dcant_zonal_ensemble %>%
    filter(data_source == "mod") %>% 
    select(lat, depth, basin_AIP, period, dcant_ensemble_mean, dcant_sd),
  dcant_zonal_all %>%
    filter(data_source == "mod_truth",
           {{config}} == unique(dcant_zonal_all${{config}})[1]) %>% 
    select(lat, depth, basin_AIP, period, dcant_mod_truth = dcant)
)

dcant_zonal_ensemble_bias <- dcant_zonal_ensemble_bias %>% 
  mutate(dcant_mean_bias = dcant_ensemble_mean - dcant_mod_truth)

dcant_zonal_ensemble_bias %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_mean_bias",
      col = "divergent",
      plot_slabs = "n",
      subtitle_text = paste("basin:",
        unique(.x$basin_AIP)
      )
    ) +
      facet_grid(. ~ period)
  )

```

### Density distribution

```{r bias_density_distribution_ensemble, fig.asp=1}

dcant_zonal_bias_all %>%
  ggplot() +
  scale_color_manual(values = c("red", "grey")) +
  geom_vline(xintercept = 0) +
  geom_density(aes(dcant_bias, group = {{config}}, col = "Individual")) +
  geom_density(data = dcant_zonal_ensemble_bias,
               aes(dcant_mean_bias, col = "Ensemble")) +
  facet_grid(period ~.) +
  coord_cartesian(xlim = c(-10, 10))

```


## Mean depth layer budgets

```{r lat_grid_budget_ensemble, fig.asp=1, eval=FALSE}

dcant_lat_grid_ensemble %>%
  ggplot(aes(lat_grid, dcant_mean)) +
  geom_hline(yintercept = 0) +
  geom_col(position = "dodge",
           fill = "grey80",
           col = "grey20") +
  geom_errorbar(aes(
    ymin = dcant_min,
    ymax = dcant_max
  ),
  col = "grey20",
  width = 0) +
  scale_color_brewer(palette = "Set1") +
  coord_flip() +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(data_source ~ period)

```


## Standard deviation

```{r ensemble_sd, fig.asp=0.9}

dcant_zonal_ensemble %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_sd",
      breaks = c(seq(0,4,0.4), Inf),
      plot_slabs = "n",
      subtitle_text = paste("basin:",
                            unique(.x$basin_AIP))
    ) +
      facet_grid(data_source ~ period)
  )


```

## SD as uncertainty

```{r ensemble_sd_uncertainty, fig.asp=0.5}

uncertainty_grid <- dcant_zonal_ensemble %>%
  filter(dcant_sd > sd_uncertainty_limit) %>% 
  distinct(depth, lat, data_source, period, basin_AIP)

uncertainty_grid <- uncertainty_grid %>%
  mutate(
    lat_grid = cut(lat, seq(-90, 90, 5), seq(-87.5, 87.5, 5)),
    lat_grid = as.numeric(as.character(lat_grid)),
    depth_grid = cut(depth, seq(0, 1e4, 500), seq(250, 1e4, 500)),
    depth_grid = as.numeric(as.character(depth_grid))
  ) %>%
  distinct(depth_grid, lat_grid, data_source, period, basin_AIP)

uncertainty_grid %>%
  filter(data_source == "obs") %>%
  ggplot() +
  geom_point(aes(lat_grid, depth_grid),
             shape = 3) +
  facet_grid(basin_AIP ~ period) +
  scale_y_reverse()

```


## SD vs bias

```{r ensemble_sd_vs_bias, fig.asp=0.5}

dcant_zonal_ensemble_bias %>% 
  ggplot(aes(dcant_mean_bias, dcant_sd)) +
  geom_bin2d() +
  scale_fill_viridis_c() +
  facet_grid(basin_AIP ~ period)


dcant_zonal_ensemble_bias %>% 
  select(dcant_ensemble_mean, dcant_mean_bias, period) %>% 
  pivot_longer(dcant_ensemble_mean:dcant_mean_bias,
               names_to = "estimate",
               values_to = "value") %>% 
  ggplot(aes(value, col=estimate, linetype = period)) +
  scale_color_brewer(palette = "Set1") +
  geom_density()

dcant_zonal_ensemble %>% 
  ggplot(aes(dcant_sd)) +
  geom_histogram() +
  facet_grid(data_source ~ period) +
  coord_cartesian(ylim = c(0,50))

```

## Composed figure

```{r composed_figure}

uncertainty_grid <- uncertainty_grid %>%
  filter(data_source == "obs",
         period != "1994 - 2014")

p_zonal_ensemble <- dcant_zonal_ensemble %>%
  filter(data_source == "obs",
         period != "1994 - 2014") %>%
  p_section_zonal_continous_depth(var = "dcant_ensemble_mean",
                                  plot_slabs = "n",
                                  title_text = NULL) +
  geom_point(data = uncertainty_grid,
             aes(lat_grid, depth_grid),
             shape = 3,
             col = "white") +
  facet_grid(basin_AIP ~ period,
             switch = "y") +
  theme(legend.position = "left",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

p_profiles <-
  dcant_profile_all %>%
  arrange(depth) %>%
  filter(period != "1994 - 2014",
         data_source == "obs") %>%
  ggplot(aes(
           dcant,
           depth,
           col = period,
           fill = "grey80",
           group = interaction({{config}}, period)
         )) +
  geom_hline(yintercept = params_global$inventory_depth_standard) +
  geom_vline(xintercept = 0) +
  geom_path() +
  scale_y_reverse(name = "Depth (m)",
                  limits = c(5000,0)) +
  scale_x_continuous(name = expression(Delta * C[ant] ~ (µmol~kg^{-1}))) +
  coord_cartesian(expand = 0) +
  scale_color_brewer(palette = "Set1") +
  facet_grid(basin_AIP ~.) +
  theme(legend.position = "top",
        legend.direction = "vertical",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())


p_layer_budget <- dcant_budget_basin_AIP_layer_ensemble %>%
  filter(data_source == "obs",
         period != "1994 - 2014") %>%
  mutate(depth =
           as.numeric(str_split(inv_depth, " - ", simplify = TRUE)[, 1]) + 250) %>%
  filter(depth < 5000) %>% 
  ggplot(aes(dcant_mean, inv_depth, col = period)) +
  geom_col(position = "dodge",
           orientation = "y",
           fill = "grey80") +
  geom_errorbar(
    aes(xmin = dcant_min,
        xmax = dcant_max),
    width = 0,
    position = position_dodge(width = 0.9)
  ) +
  scale_color_brewer(palette = "Set1", guide = "none") +
  scale_x_continuous(
    limits = c(0, NA),
    expand = c(0, 0),
    name = expression(Delta * C[ant] ~ (PgC))
  ) +
  scale_y_discrete(name = "Depth intervals (m)",
                   limits = rev) +
  facet_grid(basin_AIP ~ .) +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())


p_zonal_ensemble + p_profiles + p_layer_budget +
  plot_layout(widths = c(5,1,1)) +
  plot_annotation(tag_levels = 'a')

# ggsave("output/publication/Fig_zonal_mean.png",
#        width=15.25,
#        height=9.27)

```



# Cases vs ensemble

## Offset from mean

```{r ensemble_deviation_from_mean, fig.asp=1.2}


dcant_zonal_all <- full_join(dcant_zonal_all %>% select(-dcant_sd),
                             dcant_zonal_ensemble)

dcant_zonal_all <- dcant_zonal_all %>%
  mutate(dcant_offset = dcant - dcant_ensemble_mean)


legend_title <- expression(atop(Delta * C[ant, offset],
                                (mu * mol ~ kg ^ {
                                  -1
                                })))

dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(basin_AIP, data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_offset",
      col = "divergent",
      plot_slabs = "n",
      subtitle_text = paste("basin:",
                            unique(.x$basin_AIP),
                            "| data_source",
                            unique(.x$data_source))
    ) +
      facet_grid({{config}} ~ period)
  )

```



