---
title: "Anomalous changes"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(marelac)
```

# Data preparation

```{r read_version_IDs}

Version_IDs <- list.files(
  path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
  pattern = "v_2")

# Version_IDs <- Version_IDs[1:4]

```


## Load data

```{r read_cant_inv_files}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  cant_inv <-
    read_csv(paste(path_version_data,
                   "anom_cant_mod_inv_bias.csv",
                   sep = ""))
  
  cant_inv <- cant_inv %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins
  )
  
  cant_inv <- full_join(cant_inv, params_local)
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  duration <- sort(tref$median_year)[2] - sort(tref$median_year)[1]
  eras <- paste0(sort(tref$median_year)[1],"-", sort(tref$median_year)[2])
  
  cant_inv <- cant_inv %>% 
    mutate(duration = duration,
           eras = eras)
  
  if (exists("cant_inv_all")) {
    cant_inv_all <- bind_rows(cant_inv_all, cant_inv)
  }
  
  if (!exists("cant_inv_all")) {
    cant_inv_all <- cant_inv
  }
  
  
}

rm(cant_inv)

```

## Format column inventories

```{r calc_column_inventories_2021_beta}

cant_inv_all_long <- cant_inv_all %>%
  pivot_longer(emlr_anom:nss_projection,
               names_to = "estimate",
               values_to = "delta_cant_offset")
```


## Column inventories

```{r column_inventory_maps_regions_eras}

cant_inv_all_long %>%
  group_split(eras) %>%
  head(1) %>%
  map(
    ~ p_map_cant_inv_offset(
      df = .x,
      var = "delta_cant_offset",
      # col = "divergent",
      subtitle_text = paste("Eras:", unique(.x$eras)),
      breaks = seq(-8,8,1)
    ) +
      facet_grid(MLR_basins ~ estimate)
  )


```


# Zonal sections

## Load data

```{r read_cant_section_files}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  cant_section <-
    read_csv(paste(path_version_data,
                   "anom_cant_mod_section_bias.csv",
                   sep = ""))
  
  cant_section <- cant_section %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins
  )
  
  cant_section <- full_join(cant_section, params_local)
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  duration <- sort(tref$median_year)[2] - sort(tref$median_year)[1]
  eras <- paste0(sort(tref$median_year)[1],"-", sort(tref$median_year)[2])
  
  cant_section <- cant_section %>% 
    mutate(duration = duration,
           eras = eras)
  
  if (exists("cant_section_all")) {
    cant_section_all <- bind_rows(cant_section_all, cant_section)
  }
  
  if (!exists("cant_section_all")) {
    cant_section_all <- cant_section
  }
  
  
}

rm(cant_section)

```

## Format column inventories

```{r format_cant_section}

cant_section_all_long <- cant_section_all %>%
  pivot_longer(emlr_anom:nss_projection,
               names_to = "estimate",
               values_to = "delta_cant_offset")
```


## Plots

```{r cant_sections_regions_eras, fig.asp=0.5, eval=FALSE}

cant_section_all_long %>%
  group_split(eras, MLR_basins, estimate) %>%
  # head(1) %>%
  map(
    ~ p_section_zonal(
      df = .x,
      var = "delta_cant_offset",
      plot_slabs = "n",
      col = "divergent",
      subtitle_text = paste("Eras:", unique(.x$eras),
                            "MLR Basins:", unique(.x$MLR_basins),
                            "Estimate:", unique(.x$estimate)),
      breaks = seq(-8,8,1)
    )
  )


```


```{r cant_sections_regions_eras_facet}

legend_title <- expression(atop(Delta * C[ant, pos],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))


cant_section_all_long %>%
  group_split(eras) %>% 
  # head(1) %>%
  map(
    ~ ggplot(data = .x) +
      geom_contour_filled(aes(lat, depth, z = delta_cant_offset),
                          breaks = seq(-8, 8, 1)) +
      scale_fill_scico_d(
        palette = "vik",
        drop = FALSE,
        name = legend_title
      ) +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"))) +
      scale_y_reverse() +
      scale_x_continuous(breaks = seq(-100, 100, 40),
                         limits = c(-85, 85)) +
      facet_grid(MLR_basins ~ estimate) +
      coord_cartesian(expand = 0) +
      labs(title = paste("Eras", unique(.x$eras)))
  )


```

```{r section_bias_plots, fig.asp=1}

axis_limit <- cant_section_all %>% 
  pivot_longer(emlr_anom:nss_projection,
               names_to = "estimate",
               values_to = "bias") %>% 
  pull(bias) %>% 
  abs() %>% 
  max()

cant_section_all %>%
  group_split(eras) %>%
  # head(1) %>% 
  map(
    ~ ggplot(data = .x, aes(emlr_bias, emlr_anom)) +
      geom_hline(yintercept = 0) +
      geom_vline(xintercept = 0) +
      geom_bin2d(binwidth = 1) +
      scale_fill_viridis_c(trans = "log10") +
      coord_equal(
        xlim = c(-axis_limit, axis_limit),
        ylim = c(-axis_limit, axis_limit)
      ) +
      labs(title = paste("Eras:", unique(.x$eras))) +
      facet_grid(MLR_basins ~ basin_AIP)
  )


cant_section_all %>%
  group_split(eras) %>%
  # head(1) %>% 
  map(
    ~ ggplot(data = .x, aes(emlr_anom, nss_mod_truth)) +
      geom_hline(yintercept = 0) +
      geom_vline(xintercept = 0) +
      geom_bin2d(binwidth = 1) +
      scale_fill_viridis_c(trans = "log10") +
      coord_equal(
        xlim = c(-axis_limit, axis_limit),
        ylim = c(-axis_limit, axis_limit)
      ) +
      labs(title = paste("Eras:", unique(.x$eras))) +
      facet_grid(MLR_basins ~ basin_AIP)
  )

cant_section_all %>%
  group_split(eras) %>%
  # head(1) %>% 
  map(
    ~ ggplot(data = .x, aes(nss_mod_truth, nss_projection)) +
      geom_hline(yintercept = 0) +
      geom_vline(xintercept = 0) +
      geom_bin2d(binwidth = 1) +
      scale_fill_viridis_c(trans = "log10") +
      coord_equal(
        xlim = c(-axis_limit, axis_limit),
        ylim = c(-axis_limit, axis_limit)
      ) +
      labs(title = paste("Eras:", unique(.x$eras))) +
      facet_grid(MLR_basins ~ basin_AIP)
  )

```



# Budgets

## Load data

```{r read_cant_budget_files}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  cant_budget <-
    read_csv(paste(path_version_data,
                   "anom_cant_mod_inv_budget.csv",
                   sep = ""))
  
  cant_budget <- cant_budget %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins
  )
  
  cant_budget <- full_join(cant_budget, params_local)
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  duration <- sort(tref$median_year)[2] - sort(tref$median_year)[1]
  eras <- paste0(sort(tref$median_year)[1],"-", sort(tref$median_year)[2])
  
  cant_budget <- cant_budget %>% 
    mutate(duration = duration,
           eras = eras)
  
  if (exists("cant_budget_all")) {
    cant_budget_all <- bind_rows(cant_budget_all, cant_budget)
  }
  
  if (!exists("cant_budget_all")) {
    cant_budget_all <- cant_budget
  }
  
  
}

rm(cant_budget)

```



### Regional

```{r budgets_regional_regions_eras_2021_beta, fig.asp=1}

cant_budget_all %>%
  filter(inv_depth == params_global$inventory_depth_standard) %>% 
  ggplot(aes(estimate, cant_pos_total, fill = basin_AIP)) +
  scale_fill_brewer(palette = "PuBuGn") +
  geom_col(col = "black") +
  facet_grid(MLR_basins ~ eras) +
  theme(axis.text.x = element_text(angle = 90))

```




