---
title: "Basics"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(khroma)

```


```{r select_basin_mask, include=FALSE}

basinmask_05 <- basinmask %>% 
  filter(MLR_basins == "5") %>% 
  select(-c(MLR_basins, basin_AIP))

basinmask_05 <- basinmask_05 %>% 
  mutate(
    basin = str_replace(basin, "_", ". "),
    basin = fct_relevel(
      basin,
      "N. Pacific",
      "S. Pacific",
      "N. Atlantic",
      "S. Atlantic",
      "Indian"
    )
  )

```

# Read files


```{r define_Version_IDs_ensemble}

version_id_pattern <- "103"

# identify required version IDs

Version_IDs_1 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_1", version_id_pattern))

Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_2", version_id_pattern))

Version_IDs_3 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_3", version_id_pattern))

Version_IDs <- c(Version_IDs_1, Version_IDs_2, Version_IDs_3)

```


```{r read_parameters_ensemble}

for (i_Version_IDs in Version_IDs) {
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    MLR_basins = params_local$MLR_basins
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  
  if (exists("params_local_all_ensemble")) {
    params_local_all_ensemble <- bind_rows(params_local_all_ensemble, params_local)
  }
  
  if (!exists("params_local_all_ensemble")) {
    params_local_all_ensemble <- params_local
  }
  
  
}

rm(params_local,
   tref)


params_local_all_ensemble <- params_local_all_ensemble %>%
  select(Version_ID, period, MLR_basins, tref1, tref2)

params_local_all_ensemble <-
  params_local_all_ensemble %>%
  mutate(
    Version_ID_group = str_sub(Version_ID, 4, 4),
    Version_ID_group = case_when(
      Version_ID_group == "1" ~ "Bulk adjustment",
      Version_ID_group == "c" ~ "Cruise adjustment",
      Version_ID_group == "d" ~ "No adjustment",
      Version_ID_group == "g" ~ "No gap filling",
      Version_ID_group == "o" ~ "Reoccupation filter",
      Version_ID_group == "e" ~ "Surface eMLR(C*)",
      Version_ID_group == "n" ~ "C*(N)",
      TRUE ~ Version_ID_group
    )
  )

params_local_all_ensemble <-
  params_local_all_ensemble %>%
  mutate(
    MLR_basins = case_when(
      MLR_basins == "AIP" ~ "3",
      MLR_basins == "SO_AIP" ~ "3+SO",
      MLR_basins == "SO_5" ~ "5+SO",
      TRUE ~ MLR_basins
    )
  )


params_local_all <- params_local_all_ensemble %>% 
  filter(Version_ID %in% Version_IDs)

```

## Periods

```{r define_period_groups}

two_decades <- unique(params_local_all_ensemble$period)[1:2]

```



## Observations coverage

```{r read_coverage_grid_files}


for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # read cleaned GLODAP files
  GLODAP <- read_csv(paste(
    path_version_data,
    "GLODAPv2.2020_clean.csv",
    sep = ""
  ))
  
  GLODAP <- GLODAP %>%
    mutate(Version_ID = i_Version_IDs)
  
  if (exists("GLODAP_all")) {
    GLODAP_all <-
      bind_rows(GLODAP_all, GLODAP)
  }
  
  if (!exists("GLODAP_all")) {
    GLODAP_all <- GLODAP
  }

  
  # read cleaned GLODAP_flagging_stats files
  GLODAP_flagging_stats <- read_csv(paste(
    path_version_data,
    "GLODAP_flagging_stats.csv",
    sep = ""
  ))
  
  GLODAP_flagging_stats <- GLODAP_flagging_stats %>%
    mutate(Version_ID = i_Version_IDs)
  
  if (exists("GLODAP_flagging_stats_all")) {
    GLODAP_flagging_stats_all <-
      bind_rows(GLODAP_flagging_stats_all, GLODAP_flagging_stats)
  }
  
  if (!exists("GLODAP_flagging_stats_all")) {
    GLODAP_flagging_stats_all <- GLODAP_flagging_stats
  }
  
  # read cleaned GLODAP_adjustment_stats files
  GLODAP_adjustment_stats <- read_csv(paste(
    path_version_data,
    "GLODAP_adjustment_stats.csv",
    sep = ""
  ))
  
  GLODAP_adjustment_stats <- GLODAP_adjustment_stats %>%
    mutate(Version_ID = i_Version_IDs)
  
  if (exists("GLODAP_adjustment_stats_all")) {
    GLODAP_adjustment_stats_all <-
      bind_rows(GLODAP_adjustment_stats_all, GLODAP_adjustment_stats)
  }
  
  if (!exists("GLODAP_adjustment_stats_all")) {
    GLODAP_adjustment_stats_all <- GLODAP_adjustment_stats
  }
  
  # read cleaned GLODAP_CanyonB_filling_stats files
  GLODAP_CanyonB_filling_stats <- read_csv(paste(
    path_version_data,
    "GLODAP_CanyonB_filling_stats.csv",
    sep = ""
  ))
  
  GLODAP_CanyonB_filling_stats <- GLODAP_CanyonB_filling_stats %>%
    mutate(Version_ID = i_Version_IDs)
  
  if (exists("GLODAP_CanyonB_filling_stats_all")) {
    GLODAP_CanyonB_filling_stats_all <-
      bind_rows(GLODAP_CanyonB_filling_stats_all, GLODAP_CanyonB_filling_stats)
  }
  
  if (!exists("GLODAP_CanyonB_filling_stats_all")) {
    GLODAP_CanyonB_filling_stats_all <- GLODAP_CanyonB_filling_stats
  }

}


rm(
  GLODAP,
  GLODAP_adjustment_stats,
  GLODAP_CanyonB_filling_stats,
  GLODAP_flagging_stats
)

GLODAP_all <- full_join(GLODAP_all,
                        params_local_all)

GLODAP_adjustment_stats_all <-
  full_join(GLODAP_adjustment_stats_all,
            params_local_all)

GLODAP_CanyonB_filling_stats_all <-
  full_join(GLODAP_CanyonB_filling_stats_all,
            params_local_all)

GLODAP_flagging_stats_all <- full_join(GLODAP_flagging_stats_all,
                                       params_local_all)


GLODAP_expocodes <-
  read_tsv(
    paste(
      "/nfs/kryo/work/updata/glodapv2_2021/",
      "EXPOCODES.txt",
      sep = ""
    ),
    col_names = c("cruise", "cruise_expocode")
  )

GLODAP_all <-
  left_join(GLODAP_all, GLODAP_expocodes)

GLODAP_all <- GLODAP_all %>%
  filter(period %in% two_decades) %>%
  filter(!(period == "1994 - 2004" &
             era == "2000-2009"))

```


# Adjustment stats


```{r data_set_stats}

GLODAP_adjustment_stats_all %>% 
  group_by(era, period, adjustment, group) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  filter(adjustment == "yes") %>% 
  filter(period %in% two_decades) %>%
  filter(!(period == "1994 - 2004" &
             era == "2000-2009")) %>% 
  summarise(n = sum(n))

GLODAP_flagging_stats_all %>% 
  filter(group == "filled")

GLODAP_CanyonB_filling_stats_all %>%
  group_by(era, period, parameter, filling) %>%
  summarise(n = sum(n)) %>%
  ungroup() %>% 
  filter(filling == "filled") %>%
  filter(period %in% two_decades) %>%
  filter(!(period == "1994 - 2004" &
             era == "2000-2009")) %>% 
  summarise(n = sum(n))
  # ggplot(aes(parameter, n, fill = filling)) +
  # coord_flip() +
  # geom_col() +
  # facet_grid(era~period) +
  # scale_fill_brewer(palette = "Dark2")


```



```{r read_files_global}

GLODAP_preprocessed <-
  read_csv(
    paste(
      path_preprocessing,
      "GLODAPv2.2021_preprocessed.csv",
      sep = ""
    )
  )

```


```{r read_landseamask_file}
# land sea mask
landseamask <-
  read_csv(paste(path_files,
                  "land_sea_mask_WOA18.csv",
                  sep = ""))

```


# Time series histogram

```{r time_series_post_Gruber_2019, fig.asp=0.4, eval=FALSE}

time_histo <- GLODAP_preprocessed %>% 
  drop_na() %>% 
  mutate(version = if_else(cruise <1000, "Gruber et al. (2019)", 
                           "New observations"),
         version = if_else(cruise %in% c(1041, 1042), "Gruber et al. (2019)", version)) %>% 
  count(year, version)

GLODAP_preprocessed %>% 
  drop_na() %>% 
  mutate(version = if_else(cruise <1000, "Gruber et al. (2019)", 
                           "New observations"),
         version = if_else(cruise %in% c(1041, 1042), "Gruber et al. (2019)", version)) %>% 
  count(version)

p_time_histo_G19 <-
  time_histo %>%
  filter(version == "Gruber et al. (2019)") %>% 
  ggplot() +
  geom_col(aes(year, n, fill = version),
           col = "grey20") +
  scale_fill_manual(values = c("grey70"),
                    name = "") +
  scale_x_continuous(breaks = seq(1900, 2100, 5),
                     limits = c(1981, 2021)) +
  scale_y_continuous(limits = c(0, max(time_histo$n) + 500)) +
  coord_cartesian(expand = 0) +
  labs(title = "Observations per year") +
  theme_classic() +
  theme(axis.title = element_blank())

p_time_histo_all <-
  time_histo %>%
  mutate(version = fct_rev(version)) %>% 
  ggplot() +
  geom_col(aes(year, n, fill = version),
           col = "grey20") +
  scale_fill_manual(values = c("darkgoldenrod1", "grey70"),
                    name = "") +
  scale_x_continuous(breaks = seq(1900, 2100, 5),
                     limits = c(1981, 2021)) +
  scale_y_continuous(limits = c(0, max(time_histo$n) + 500)) +
  coord_cartesian(expand = 0) +
  labs(title = "Observations per year") +
  theme_classic() +
  theme(axis.title = element_blank())


p_time_histo_G19
p_time_histo_all


# ggsave(plot = p_time_histo_G19,
#        path = here::here("output/publication"),
#        filename = "time_histo_G19.png",
#        height = 2,
#        width = 10)

# ggsave(plot = p_time_histo_all,
#        path = here::here("output/publication"),
#        filename = "FigS_coverage_time_series.png",
#        height = 4,
#        width = 10)

rm(
p_time_histo_G19,
p_time_histo_all
)

```



```{r time_series_per_basin, fig.asp=0.4}

GLODAP_all <-
  inner_join(GLODAP_all %>% select(-basin),
             basinmask_05)


time_histo <- GLODAP_all %>%
  count(year, basin) %>%
  mutate(basin = fct_relevel(
    basin,
    "N. Pacific",
    "S. Pacific",
    "N. Atlantic",
    "S. Atlantic",
    "Indian"
  ))

p_time_histo_basin <-
  time_histo %>%
  ggplot() +
  annotate("rect", xmin = 1999.5, xmax=2009.5,
                ymin = 0, ymax = Inf,
            fill = "grey80", col="transparent") +
  geom_col(
    aes(year, n, fill = basin),
    col = "grey20",
    # fill = "grey50",
    linewidth = 0.3,
    width = 0.7
  ) +
  scale_fill_brewer(palette = "Paired") +
  scale_x_continuous(breaks = seq(1994, 2014, 10)) +
  scale_y_continuous(limits = c(0, NA), expand = c(0, 0)) +
  labs(y = "Observations per year") +
  # facet_grid(basin~.)+
  theme(axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.08,0.65),
        legend.background = element_rect(fill = "transparent"))

p_time_histo_basin


# ggsave(plot = p_time_histo_basin,
#        path = here::here("output/publication"),
#        filename = "FigS_observations_coverage_time_series.png",
#        height = 6,
#        width = 7)

# rm(p_time_histo_basin)

```

```{r number_observations}

time_histo %>% 
  summarise(n = sum(n))

GLODAP_all %>% 
  count(era)

```


# Coverage maps

## Robinson

```{r coverage_maps_robinson}

cruises_phosphate_gap_fill <-
  c("33MW19930704",
    "33RO20030604",
    "33RO20050111",
    "33RO19980123")

cruises_talk_gap_fill <-
  c("06AQ19980328")

cruises_talk_calc <-
  c("06MT19900123",
    "316N19920502",
    "316N19921006")

GLODAP_all_coverage <- GLODAP_all %>% 
  distinct(lat, lon, era, cruise_expocode) %>% 
  mutate(gap_filling = case_when(
    cruise_expocode %in% cruises_phosphate_gap_fill ~ 1,
    cruise_expocode %in% cruises_talk_gap_fill ~ 2,
    cruise_expocode %in% cruises_talk_calc ~ 3,
    cruise_expocode %in% "31DS19940126" ~ 4,
    TRUE ~ 5
  )) %>% 
  distinct(lat, lon, era, gap_filling)

GLODAP_all_coverage_raster <- rast(GLODAP_all_coverage %>% 
                                     relocate(lon, lat) %>% 
                                     pivot_wider(names_from = era,
                                                 values_from = gap_filling,
                                                 values_fn = ~first(.x)),
                                   crs = "+proj=longlat")


GLODAP_all_coverage_raster <- project(GLODAP_all_coverage_raster, target_crs,
                                      method = "near")

GLODAP_all_coverage_tibble <- GLODAP_all_coverage_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  pivot_longer(cols = -c("lon", "lat"),
               names_to = "era",
               values_to = "gap_filling") %>% 
  drop_na()

GLODAP_all_coverage_tibble <- GLODAP_all_coverage_tibble %>% 
  mutate(gap_filling = case_when(
    gap_filling == 1 ~ "Phosphate from CANYON-B",
    gap_filling == 2 ~ "TA from CANYON-B",
    gap_filling == 3 ~ "TA calculated from other variables",
    gap_filling == 4 ~ "Nitrate qc-flag not met",
    TRUE ~ "All quality criteria fulfilled"
  ))


coverage_map <- 
  ggplot() +
  geom_tile(
    data = GLODAP_all_coverage_tibble %>%
      filter(gap_filling == "All quality criteria fulfilled"),
    aes(
      x = lon,
      y = lat,
      height = 1.5e5,
      width = 1.5e5,
      fill = gap_filling
    )
  )+
  geom_tile(
    data = GLODAP_all_coverage_tibble %>%
      filter(gap_filling != "All quality criteria fulfilled"),
    aes(
      x = lon,
      y = lat,
      height = 1.5e5,
      width = 1.5e5,
      fill = gap_filling
    )
  )+
  geom_sf(data = worldmap_trans, fill = "grey90", col = "grey90") +
  geom_sf(data = coastline_trans, linewidth = 0.3) +
  geom_sf(data = bbox_graticules_trans, linewidth = 0.5) +
  coord_sf(
    crs = target_crs,
    ylim = lat_lim,
    xlim = lon_lim,
    expand = FALSE
  ) +
  facet_wrap( ~ era, ncol = 2) +
  scale_color_okabeito(guide = "none") +
  scale_fill_okabeito() +
  theme_void() +
  theme(legend.position = c(0.8,0.25),
        legend.title = element_blank())

coverage_map

wrap_plots(p_time_histo_basin,
           coverage_map, ncol = 1) +
  plot_layout(heights = c(1, 2))  +
  plot_annotation(tag_levels = 'A')

ggsave(
  path = here::here("output/publication"),
  filename = "Fig_observations_coverage.png",
  height = 6,
  width = 8,
  dpi = 600
)

```


## Mercator

```{r coverage_maps}

cruises_phosphate_gap_fill <-
  c("33MW19930704",
    "33RO20030604",
    "33RO20050111",
    "33RO19980123")

cruises_talk_gap_fill <-
  c("06AQ19980328")

cruises_talk_calc <-
  c("06MT19900123",
    "316N19920502",
    "316N19921006")

GLODAP_all_coverage <- GLODAP_all %>% 
  distinct(lat, lon, era, cruise_expocode) %>% 
  mutate(gap_filling = case_when(
    cruise_expocode %in% cruises_phosphate_gap_fill ~ "Phosphate from CANYON-B",
    cruise_expocode %in% cruises_talk_gap_fill ~ "TA from CANYON-B",
    cruise_expocode %in% cruises_talk_calc ~ "TA calculated from other variables",
    cruise_expocode %in% "31DS19940126" ~ "Nitrate qc-flag not met",
    TRUE ~ "All quality criteria fulfilled"
  )) %>% 
  distinct(lat, lon, era, gap_filling)

colour("bright")(7)

coverage_map <- map +
  geom_tile(data = GLODAP_all_coverage %>% 
              filter(gap_filling == "All quality criteria fulfilled"),
            aes(lon, lat,
            fill = gap_filling, col = gap_filling,
                height = 2, width = 2)) +
  geom_tile(data = GLODAP_all_coverage %>% 
              filter(gap_filling != "All quality criteria fulfilled"),
            aes(lon, lat,
            fill = gap_filling, col = gap_filling,
                height = 2, width = 2)) +
  facet_wrap( ~ era, ncol = 2) +
  scale_color_okabeito(guide = "none") +
  scale_fill_okabeito() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.7,0.3),
        legend.title = element_blank())

wrap_plots(p_time_histo_basin,
           coverage_map, ncol = 1) +
  plot_layout(heights = c(1, 2))  +
  plot_annotation(tag_levels = 'A')

rm(coverage_map, 
   GLODAP_all_coverage, GLODAP_expocodes,
   GLODAP_grid_era_all)


rm(cruises_phosphate_gap_fill,
   cruises_talk_gap_fill,
   cruises_talk_calc)

```


# Basin maps

## MLR basins

```{r basin_maps}

basinmask <- basinmask %>% 
  mutate(
    MLR_basins = case_when(
      MLR_basins == "AIP" ~ "3",
      MLR_basins == "SO_AIP" ~ "3+SO",
      MLR_basins == "SO_5" ~ "5+SO",
      TRUE ~ MLR_basins
    )
  )


MLR_basins_in <- c("1", "2", "3", "5", "3+SO", "5+SO")

basinmask <- basinmask %>%
  filter(MLR_basins %in% MLR_basins_in)

basinmask <- basinmask %>% 
  group_by(MLR_basins) %>% 
  mutate(basin = as.character(as.numeric(as.factor(basin)))) %>% 
  ungroup()

map +
  geom_raster(data = basinmask,
              aes(lon, lat, fill = basin)) +
  scale_fill_muted(guide = "none") +
  facet_wrap( ~ MLR_basins) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())


basinmask_robin <- basinmask %>% 
  # mutate(basin = as.numeric(basin)) %>% 
  select(-basin_AIP)

basinmask_robin %>% distinct(basin) %>% pull()


basinmask_robin_raster <- rast(basinmask_robin %>% 
                                     relocate(lon, lat) %>% 
                                     pivot_wider(names_from = MLR_basins,
                                                 values_from = basin),
                                   crs = "+proj=longlat")


basinmask_robin_raster <- project(basinmask_robin_raster, target_crs, method = "near")

basinmask_robin_tibble <- basinmask_robin_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  pivot_longer(cols = -c("lon", "lat"),
               names_to = "MLR_basins",
               values_to = "basin") %>% 
  drop_na() %>% 
  mutate(basin = as.character(basin))

basin_maps <-
  ggplot() +
  geom_raster(
    data = basinmask_robin_tibble,
    aes(
      x = lon,
      y = lat,
      fill = basin
    )
  ) +
  geom_sf(data = worldmap_trans, fill = "grey90", col = "grey90") +
  geom_sf(data = coastline_trans, linewidth = 0.3) +
  geom_sf(data = bbox_graticules_trans, linewidth = 0.5) +
  coord_sf(
    crs = target_crs,
    ylim = lat_lim,
    xlim = lon_lim,
    expand = FALSE
  ) +
  facet_wrap( ~ MLR_basins, ncol = 3) +
  scale_fill_okabeito(guide = "none", reverse = TRUE)  +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_rect(colour = "transparent"),
    strip.background = element_blank()
  )

basin_maps

# ggsave(plot = basin_maps,
#        path = here::here("output/publication"),
#        filename = "FigS_basin_masks.png",
#        height = 3,
#        width = 8,
#        dpi = 600)

```


```{r global_section_map}

# prepare section basin files

section_global_coordinates_basin_raster <-
  rast(
    section_global_coordinates_basin %>%
      mutate(
        dist = 1,
        band = case_when(band == "Southern" ~ "Southern\nOcean",
                         TRUE ~ band)
      ) %>%
      pivot_wider(names_from = band,
                  values_from = dist),
    crs = "+proj=longlat"
  )

# center <- -160
# boundary <- center + 180
# target_crs <- paste0("+proj=robin +over +lon_0=", center)

section_global_coordinates_basin_raster <-
  project(section_global_coordinates_basin_raster, target_crs, method = "near")

section_global_coordinates_basin_tibble <-
  section_global_coordinates_basin_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  pivot_longer(
    cols = -c("lon", "lat"),
    names_to = "band",
    values_to = "coverage"
  ) %>%
  drop_na() %>%
  mutate(band = as.character(band))

# prepare section file

section_global_coordinates_raster <-
  rast(section_global_coordinates,
       crs = "+proj=longlat")

section_global_coordinates_raster <-
  project(section_global_coordinates_raster, target_crs, method = "near")

section_global_coordinates_tibble <-
  section_global_coordinates_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  drop_na()

section_global_coordinates_tibble <-
  section_global_coordinates_tibble %>% 
  group_by(dist) %>% 
  summarise(lon = mean(lon),
            lat = mean(lat)) %>% 
  ungroup() %>% 
  mutate(dist = cut(dist, seq(0,40,10),
                    labels = c("0-10", "10-20", "20-30", "30-40")))


global_section_map <-
  ggplot() +
  geom_raster(data = section_global_coordinates_basin_tibble %>%
                filter(band == "Atlantic"),
              aes(
                x = lon,
                y = lat,
                fill = band,
                alpha = 0.3
              )) +
  geom_raster(data = section_global_coordinates_basin_tibble %>%
                filter(band == "Southern\nOcean"),
              aes(
                x = lon,
                y = lat,
                fill = band,
                alpha = 0.3
              )) +
  geom_raster(data = section_global_coordinates_basin_tibble %>%
                filter(band == "Pacific"),
              aes(
                x = lon,
                y = lat,
                fill = band,
                alpha = 0.3
              )) +
  scale_fill_mediumcontrast(name = "Averaging\nareas") +
  # scale_fill_grey() +
  geom_path(
    data = section_global_coordinates_tibble %>%
      filter(lon > 0),
    aes(x = lon,
        y = lat,
        color = dist),
    linewidth = 1
  ) +
  geom_path(
    data = section_global_coordinates_tibble %>%
      filter(lon < 0),
    aes(x = lon,
        y = lat,
        color = dist),
    linewidth = 1
  ) +
  scale_color_grey(start = 0.7,end = 0, name = "Distance\nalong\nsection\n(1000 km)") +
  geom_sf(data = worldmap_trans, fill = "grey90", col = "grey90") +
  geom_sf(data = coastline_trans, linewidth = 0.3) +
  geom_sf(data = bbox_graticules_trans, linewidth = 0.3) +
  coord_sf(
    crs = target_crs,
    ylim = lat_lim,
    xlim = lon_lim,
    expand = FALSE
  ) +
  guides(fill = guide_legend(override.aes = list(alpha = 0.3)),
         alpha = "none") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_rect(colour = "transparent"),
    strip.background = element_blank(),
    panel.grid.major = element_blank(),
    legend.direction = "vertical", legend.box = "horizontal"
  )

design <- "AAAA
           #BB#"

wrap_plots(A = basin_maps, B = global_section_map, design = design) +
  plot_layout(heights = c(3, 2))  +
  plot_annotation(tag_levels = 'A')

ggsave(path = here::here("output/publication"),
       filename = "FigS_basin_masks.png",
       height = 6,
       width = 10,
       dpi = 200)

```




## 5 basins

```{r 5_basin_map}

MLR_basins_in <- c("5")

basinmask <- basinmask %>%
  filter(MLR_basins %in% MLR_basins_in)

basinmask <- basinmask %>% 
  group_by(MLR_basins) %>% 
  mutate(basin = as.character(as.numeric(as.factor(basin)))) %>% 
  ungroup()


basinmask <- basinmask %>%
  mutate(
    basin = fct_recode(
      basin,
      "N. Pacific" = "3",
      "S. Pacific" = "5",
      "N. Atlantic" = "2",
      "S. Atlantic" = "4",
      "Indian" = "1"
    )
  )

basinmask <- basinmask %>%
  mutate(basin = fct_relevel(
    basin,
    "N. Pacific",
    "S. Pacific",
    "N. Atlantic",
    "S. Atlantic",
    "Indian"
  ))

basin_maps <-
  map +
  geom_raster(data = basinmask,
              aes(lon, lat, fill = basin)) +
  scale_fill_bright(guide = "none") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank())

basin_maps

# ggsave(plot = basin_maps,
#        path = here::here("output/publication"),
#        filename = "FigS_basin_mask_5.png",
#        height = 5,
#        width = 10)

```

## Area scaling

```{r area_scaling}

mapped_ocean_mask <- full_join(
  landseamask %>% 
    filter(region == "ocean") %>% 
    select(lon, lat),
  basinmask %>% 
    select(lon, lat) %>% 
    mutate(mapped_ocean = "1")
) %>% 
  mutate(mapped_ocean = replace_na(mapped_ocean, "0"))


map +
  geom_raster(data = mapped_ocean_mask,
              aes(lon, lat, fill = mapped_ocean)) +
  scale_fill_brewer(palette = "Set1") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

mapped_ocean_mask %>% 
  mutate(surface_area = earth_surf(lat, lon)) %>% 
  group_by(mapped_ocean) %>% 
  summarise(surface_area = sum(surface_area)) %>% 
  ungroup() %>% 
  mutate(surface_area_ratio = surface_area / lead(surface_area))
  
```


# coverage maps all

```{r coverage_maps_simple}

GLODAP_era_grid <- GLODAP_all %>% 
  group_by(lon, lat, era) %>% 
  summarise(year_max = max(year),
            year_min = min(year)) %>% 
  ungroup() %>% 
  drop_na()

coverage_map <-
  map +
  geom_tile(data = GLODAP_era_grid,
              aes(lon, lat, 
              fill = "X")) +
  scale_fill_brewer(palette = "Dark2", guide = "none") +
  facet_wrap(~ era, ncol = 2) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank())

coverage_map


```

