---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
```

# Global

## Read files

```{r read_files_global}

# identify required version IDs

Version_IDs_1 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_11")

Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_21")

Version_IDs <- c(Version_IDs_1, Version_IDs_2)
rm(Version_IDs_1, Version_IDs_2)

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  CANYON_B_cleaning_GLODAP_sample_removal_grid <-
    read_csv(paste(path_version_data,
                   "CANYON_B_cleaning_GLODAP_sample_removal_grid.csv",
                   sep = ""))
  
  CANYON_B_cleaning_GLODAP_sample_removal_grid <- CANYON_B_cleaning_GLODAP_sample_removal_grid %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    CANYON_B_sample_SD = as.character(params_local$CANYON_B_sample_SD)
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  
  if (exists("cleaning_grid")) {
    cleaning_grid <-
      bind_rows(cleaning_grid, CANYON_B_cleaning_GLODAP_sample_removal_grid)
  }
  
  if (!exists("cleaning_grid")) {
    cleaning_grid <- CANYON_B_cleaning_GLODAP_sample_removal_grid
  }
  
  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(CANYON_B_cleaning_GLODAP_sample_removal_grid,
   params_local,
   tref)

cleaning_grid <- full_join(cleaning_grid,
                           params_local_all)


```

## Maps

```{r cleaning_maps}

cleaning_grid %>%
  group_by(parameter) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ map +
      geom_raster(data = .x,
                  aes(lon, lat, fill = removal_ratio)) +
      scale_fill_viridis_c(direction = -1, na.value = "red") +
      facet_grid(CANYON_B_sample_SD ~ era) +
      labs(title = "Maps of removed samples",
           subtitle = unique(.x$parameter)) +
      theme(legend.title = element_blank())
  )


```

