---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(patchwork)

```

# Bias thresholds

```{r define_bias_threshold}

global_bias_rel_max <- 10
regional_bias_rel_max <- 20

```

# Basins

```{r cases_cosidered}

MLR_basins_in <- c("1", "2", "AIP", "SO", "5", "SO_AIP")

```


# Read files

```{r define_Version_IDs}

# identify required version IDs

Version_IDs_1 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_10")

Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_20")

Version_IDs_3 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_30")

# Version_IDs <- c(Version_IDs_1, Version_IDs_2)
Version_IDs <- c(Version_IDs_1, Version_IDs_2, Version_IDs_3)
# rm(Version_IDs_1, Version_IDs_2)
rm(Version_IDs_1, Version_IDs_2, Version_IDs_3)

```


## Global

```{r read_files_global}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_budget_global <-
    read_csv(paste(path_version_data,
                   "dcant_budget_global.csv",
                   sep = ""))
  
  dcant_budget_global_mod_truth <-
    read_csv(paste(
      path_version_data,
      "dcant_budget_global_mod_truth.csv",
      sep = ""
    ))
  
  dcant_budget_global_bias <-
    read_csv(paste(path_version_data,
                   "dcant_budget_global_bias.csv",
                   sep = ""))
  
  dcant_budget_global <- bind_rows(dcant_budget_global,
                                      dcant_budget_global_mod_truth)
  
  dcant_budget_global <- dcant_budget_global %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_global_bias <- dcant_budget_global_bias %>%
    mutate(Version_ID = i_Version_IDs)

  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  
  if (exists("dcant_budget_global_all")) {
    dcant_budget_global_all <-
      bind_rows(dcant_budget_global_all, dcant_budget_global)
  }
  
  if (!exists("dcant_budget_global_all")) {
    dcant_budget_global_all <- dcant_budget_global
  }
  
  if (exists("dcant_budget_global_bias_all")) {
    dcant_budget_global_bias_all <-
      bind_rows(dcant_budget_global_bias_all,
                dcant_budget_global_bias)
  }

  if (!exists("dcant_budget_global_bias_all")) {
    dcant_budget_global_bias_all <- dcant_budget_global_bias
  }
  
  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

params_local_all <-
  params_local_all %>%
  mutate(period = factor(period, c("1994 - 2004", "2004 - 2014", "1994 - 2014")))

unique(params_local_all$period)

rm(
  dcant_budget_global,
  dcant_budget_global_bias,
  dcant_budget_global_mod_truth,
  params_local,
  tref
)

dcant_budget_global_all <- full_join(dcant_budget_global_all,
                                     params_local_all)

dcant_budget_global_bias_all <-
  full_join(dcant_budget_global_bias_all,
            params_local_all)



```

```{r filter_standard_inventory_depth_global}

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

dcant_budget_global_all_depth <- dcant_budget_global_all

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
  filter(estimate == "dcant") %>%
  select(-c(estimate))

dcant_budget_global_bias_all_depth <- dcant_budget_global_bias_all

dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```

```{r select_cases}

dcant_budget_global_all <- dcant_budget_global_all %>% 
  filter(MLR_basins %in% MLR_basins_in)

dcant_budget_global_bias_all <- dcant_budget_global_bias_all  %>% 
  filter(MLR_basins %in% MLR_basins_in)


```

## Regional


```{r read_files_regional}

# Version_IDs <- Version_IDs[1:length(Version_IDs)-1]

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_budget_basin_AIP <-
    read_csv(paste(path_version_data,
                   "dcant_budget_basin_AIP.csv",
                   sep = ""))
  
  dcant_budget_basin_AIP_mod_truth <-
    read_csv(paste(
      path_version_data,
      "dcant_budget_basin_AIP_mod_truth.csv",
      sep = ""
    ))
  
  dcant_budget_basin_AIP_bias <-
    read_csv(paste(path_version_data,
                   "dcant_budget_basin_AIP_bias.csv",
                   sep = ""))
  
  dcant_budget_basin_AIP <- bind_rows(dcant_budget_basin_AIP,
                                      dcant_budget_basin_AIP_mod_truth)
  
  dcant_budget_basin_AIP <- dcant_budget_basin_AIP %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_basin_AIP_bias <- dcant_budget_basin_AIP_bias %>%
    mutate(Version_ID = i_Version_IDs)
  if (exists("dcant_budget_basin_AIP_all")) {
    dcant_budget_basin_AIP_all <-
      bind_rows(dcant_budget_basin_AIP_all, dcant_budget_basin_AIP)
  }
  
  if (!exists("dcant_budget_basin_AIP_all")) {
    dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP
  }
  
  if (exists("dcant_budget_basin_AIP_bias_all")) {
    dcant_budget_basin_AIP_bias_all <-
      bind_rows(dcant_budget_basin_AIP_bias_all,
                dcant_budget_basin_AIP_bias)
  }
  
  if (!exists("dcant_budget_basin_AIP_bias_all")) {
    dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias
  }
  
}

rm(
  dcant_budget_basin_AIP,
  dcant_budget_basin_AIP_bias,
  dcant_budget_basin_AIP_mod_truth
)

dcant_budget_basin_AIP_all <- full_join(dcant_budget_basin_AIP_all,
                                        params_local_all)

dcant_budget_basin_AIP_bias_all <-
  full_join(dcant_budget_basin_AIP_bias_all,
            params_local_all)

```

```{r filter_standard_inventory_depth_regional}

dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

dcant_budget_basin_AIP_all_depth <- dcant_budget_basin_AIP_all

dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias_all %>%
  filter(estimate == "dcant") %>% 
  select(-c(estimate))

dcant_budget_basin_AIP_bias_all_depth <- dcant_budget_basin_AIP_bias_all

dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```


```{r select_cases_regional}

dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP_all %>% 
  filter(MLR_basins %in% MLR_basins_in)

dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias_all  %>% 
  filter(MLR_basins %in% MLR_basins_in)


```

# Global

## Individual cases

### Absoulte values

```{r cases_absolute_global}

legend_title = expression(atop(Delta * C[ant],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

dcant_budget_global_all %>%
  ggplot(aes(period, dcant, col = MLR_basins)) +
  geom_jitter(width = 0.05, height = 0) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  facet_grid(. ~ data_source) +
  ylim(0,NA) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())


```

### Biases

```{r cases_bias_global}

dcant_budget_global_bias_all %>%
  ggplot(aes(period, dcant_bias, col = MLR_basins)) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = expression(atop(Delta * C[ant] ~ bias,
                               (mu * mol ~ kg ^ {-1})))) +
  geom_point()

p_global_bias <- 
  dcant_budget_global_bias_all %>%
  ggplot() +
  geom_hline(yintercept = global_bias_rel_max * c(-1,1),
             linetype = 2) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = expression(Delta * C[ant] ~ bias ~ ("%")),
       title = "Model-based assesment") +
  theme(axis.title.x = element_blank()) +
  geom_point(aes(period, dcant_bias_rel, col = MLR_basins),
             alpha = 0.7) +
    theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

p_global_bias

```

# Regional

## Individual cases

### Absoulte values

```{r cases_absolute, fig.asp=0.9}

dcant_budget_basin_AIP_all %>%
  ggplot(aes(period, dcant, col = MLR_basins)) +
  geom_jitter(width = 0.05, height = 0) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  facet_grid(basin_AIP ~ data_source) +
  ylim(0,NA) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

```

### Biases

```{r cases_bias, fig.asp=0.9}

dcant_budget_basin_AIP_bias_all %>%
  ggplot(aes(period, dcant_bias, col=MLR_basins)) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(basin_AIP ~ .)

dcant_budget_basin_AIP_bias_all %>%
  ggplot() +
  geom_tile(aes(y = 0, height = regional_bias_rel_max * 2,
                x = "2004 - 2014", width = Inf,
                fill = "bias\nthreshold"), alpha = 0.5) +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = "grey70", name = "") +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = expression(Delta ~ C[ant] ~ bias)) +
  theme(axis.title.x = element_blank()) +
  geom_jitter(aes(period, dcant_bias_rel, col = MLR_basins),
              width = 0.05, height = 0) +
  facet_grid(basin_AIP ~ .)

p_regional_bias <- 
  dcant_budget_basin_AIP_bias_all %>%
  ggplot() +
  geom_hline(yintercept = regional_bias_rel_max * c(-1,1),
             linetype = 2) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = expression(Delta * C[ant] ~ bias ~ ("%")),
       title = "Model-based assesment") +
  theme(axis.title.x = element_blank()) +
  geom_point(aes(period, dcant_bias_rel, col = MLR_basins),
             alpha = 0.7) +
    theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank()) +
  facet_grid(. ~ basin_AIP) +
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank()
)

p_regional_bias


```


# Ensemble

## Members

```{r filter_ensemble_members}

ensemble_MLR_basins_global <- dcant_budget_global_bias_all %>% 
  filter(dcant_bias_rel < global_bias_rel_max) %>% 
  count(MLR_basins) %>% 
  filter(n == 3) %>% 
  pull(MLR_basins)

print("Global criterion")
ensemble_MLR_basins_global


ensemble_MLR_basins_regional <- dcant_budget_basin_AIP_bias_all %>% 
  filter(dcant_bias_rel < regional_bias_rel_max) %>% 
  count(MLR_basins) %>% 
  filter(n == 9) %>% 
  pull(MLR_basins)

print("Regional criterion")
ensemble_MLR_basins_regional

ensemble_MLR_basins <-
  intersect(ensemble_MLR_basins_global, ensemble_MLR_basins_regional)


print("Both criteria")
ensemble_MLR_basins
rm(ensemble_MLR_basins_global, ensemble_MLR_basins_regional)

```

## Global

```{r calc_ensemble_metrics_global}

dcant_budget_global_all_in <- dcant_budget_global_all %>% 
  filter(data_source %in% c("mod", "obs"),
         MLR_basins %in% ensemble_MLR_basins)

dcant_budget_global_ensemble <- dcant_budget_global_all_in %>% 
  group_by(data_source, period) %>% 
  summarise(dcant_mean = mean(dcant),
            dcant_sd = sd(dcant),
            dcant_range = max(dcant)- min(dcant)) %>% 
  ungroup()


```

### Mean

```{r ensemble_mean_global, fig.asp=0.5}

legend_title = expression(Delta * C[ant]~(PgC))

ggplot() +
  geom_col(data = dcant_budget_global_ensemble,
           aes(x = period,
               y = dcant_mean),
           fill = "darkgrey") +
  geom_errorbar(
    data = dcant_budget_global_ensemble,
    aes(
      x = period,
      y = dcant_mean,
      ymax = dcant_mean + dcant_sd,
      ymin = dcant_mean - dcant_sd
    ),
    width = 0.1
  ) +
  geom_point(
    data = dcant_budget_global_all,
    aes(period, dcant, col = MLR_basins),
    alpha = 0.7,
    position = position_jitter(width = 0.2, height = 0)
  ) +
  scale_y_continuous(limits = c(0,70), expand = c(0,0)) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  facet_grid(. ~ data_source) +
  labs(y = legend_title) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

p_global_dcant <- ggplot() +
  geom_col(data = dcant_budget_global_ensemble %>% 
             filter(data_source == "obs"),
           aes(x = period,
               y = dcant_mean),
           fill = "darkgrey") +
    geom_point(
    data = dcant_budget_global_all %>% 
             filter(data_source == "obs"),
    aes(period, dcant, col = MLR_basins),
    alpha = 0.7,
    position = position_jitter(width = 0.1, height = 0)
  ) +
  geom_errorbar(
    data = dcant_budget_global_ensemble %>% 
             filter(data_source == "obs"),
    aes(
      x = period,
      y = dcant_mean,
      ymax = dcant_mean + dcant_sd,
      ymin = dcant_mean - dcant_sd
    ),
    width = 0.1
  ) +
  scale_y_continuous(limits = c(0,70), expand = c(0,0)) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = legend_title,
       title = "Observation-based results") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())

p_global_dcant_bias <-
p_global_dcant / p_global_bias +
  plot_layout(guides = 'collect',
              heights = c(2,1))

p_global_dcant_bias

ggsave(plot = p_global_dcant_bias,
       path = "output/publication",
       filename = "global_dcant.png",
       height = 5,
       width = 5)

rm(p_global_bias, p_global_dcant, p_global_dcant_bias)

```

### Sum decades

```{r summed_decades}

dcant_budget_global_all_in_sum <-
  dcant_budget_global_all_in %>%
  filter(period != "1994 - 2014") %>%
  arrange(tref1) %>%
  group_by(data_source, MLR_basins) %>%
  mutate(dcant = dcant + lag(dcant)) %>% 
  ungroup() %>%
  drop_na() %>% 
  mutate(estimate = "sum")

dcant_budget_global_all_in_sum <-
  bind_rows(
    dcant_budget_global_all_in_sum,
    dcant_budget_global_all_in %>%
      filter(period == "1994 - 2014") %>%
      mutate(estimate = "direct")
  )

ggplot() +
  geom_point(
    data = dcant_budget_global_all_in_sum,
    aes(estimate, dcant, col = MLR_basins),
    alpha = 0.7,
    position = position_jitter(width = 0, height = 0)
  ) +
  scale_y_continuous(limits = c(0,70), expand = c(0,0)) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  facet_grid(. ~ data_source) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

```



### Mean bias

```{r ensemble_mean_bias_global}

dcant_budget_global_ensemble_bias <- full_join(
  dcant_budget_global_ensemble %>%
    filter(data_source == "mod") %>% 
    select(period, dcant_mean, dcant_sd),
  dcant_budget_global_all %>%
    filter(data_source == "mod_truth",
           MLR_basins == "2") %>% 
    select(period, dcant)
)

dcant_budget_global_ensemble_bias <- dcant_budget_global_ensemble_bias %>% 
  mutate(dcant_mean_bias = dcant_mean - dcant,
         dcant_mean_bias_rel = 100 * dcant_mean_bias / dcant)

dcant_budget_global_ensemble_bias %>%
  ggplot(aes(period, dcant_mean_bias)) +
  geom_hline(yintercept = 0) +
  geom_point()

dcant_budget_global_ensemble_bias %>%
  ggplot(aes(period, dcant_mean_bias_rel)) +
  geom_hline(yintercept = 0) +
  geom_point()

```

### SD vs bias

```{r ensemble_sd_vs_bias_global, fig.asp=0.5}

dcant_budget_global_ensemble_bias %>% 
  ggplot(aes(dcant_mean_bias, dcant_sd, col = period)) +
  geom_point() +
  xlim(0, NA) +
  ylim(0, NA)

```


### Vertical patterns

#### Absoulte values

```{r cases_absolute_depth_global, fig.asp=0.9}

dcant_budget_global_all_depth %>%
  filter(MLR_basins %in% ensemble_MLR_basins) %>% 
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~  ggplot(data = .x,
              aes(dcant, MLR_basins, fill=period)) +
      geom_vline(xintercept = 0) +
      geom_col(position = "dodge") +
      scale_fill_brewer(palette = "Dark2") +
      facet_grid(inv_depth ~ .) +
      labs(title = paste("data_source:", unique(.x$data_source)))
  )


```

#### Biases

```{r cases_bias_depth_global, fig.asp=0.9}

dcant_budget_global_bias_all_depth %>%
    filter(MLR_basins %in% ensemble_MLR_basins) %>% 
  ggplot(aes(dcant_bias, MLR_basins, fill=period)) +
  geom_vline(xintercept = 0) +
  geom_col(position = "dodge") +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ .)

```

```{r cases_bias_rel_depth_global, fig.asp=0.9}

dcant_budget_global_bias_all_depth %>%
    filter(MLR_basins %in% ensemble_MLR_basins) %>% 
  ggplot(aes(dcant_bias_rel, MLR_basins, fill = period)) +
  geom_vline(xintercept = 0) +
  geom_col(position = "dodge") +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ .)

```


```{r clean_environment}

rm(dcant_budget_global_all,
   dcant_budget_global_all_depth,
   dcant_budget_global_bias_all,
   dcant_budget_global_bias_all_depth,
   dcant_budget_global_ensemble,
   dcant_budget_global_ensemble_bias,
   params_local_all)

```

## Regional

```{r calc_ensemble_metrics}

dcant_budget_basin_AIP_ensemble <- dcant_budget_basin_AIP_all %>% 
  filter(data_source %in% c("mod", "obs"),
         MLR_basins %in% ensemble_MLR_basins,
         MLR_basins %in% ensemble_MLR_basins) %>% 
  group_by(basin_AIP, data_source, period) %>% 
  summarise(dcant_mean = mean(dcant),
            dcant_sd = sd(dcant),
            dcant_range = max(dcant)- min(dcant)) %>% 
  ungroup()


```

### Mean

```{r ensemble_mean, fig.asp=0.5}

dcant_budget_basin_AIP_ensemble %>%
  ggplot(aes(period, dcant_mean, col=basin_AIP)) +
  geom_pointrange(aes(ymax = dcant_mean + dcant_sd,
                      ymin = dcant_mean - dcant_sd),
                  shape = 21) +
  facet_grid(. ~ data_source)



p_regional_dcant <- ggplot() +
  geom_col(
    data = dcant_budget_basin_AIP_ensemble %>%
      filter(data_source == "obs"),
    aes(x = period,
        y = dcant_mean),
    fill = "darkgrey"
  ) +
  geom_point(
    data = dcant_budget_basin_AIP_all %>%
      filter(data_source == "obs"),
    aes(period, dcant, col = MLR_basins),
    position = position_jitter(width = 0.1, height = 0),
    alpha = 0.7
  ) +
  geom_errorbar(
    data = dcant_budget_basin_AIP_ensemble %>%
      filter(data_source == "obs"),
    aes(
      x = period,
      y = dcant_mean,
      ymax = dcant_mean + dcant_sd,
      ymin = dcant_mean - dcant_sd
    ),
    width = 0.1
  ) +
  scale_y_continuous(limits = c(0, 35), expand = c(0, 0)) +
  scale_color_brewer(palette = "Dark2", name = "basin\nseparation") +
  labs(y = legend_title,
       title = "Observation-based results") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(. ~ basin_AIP)

p_regional_dcant_bias <-
p_regional_dcant / p_regional_bias +
  plot_layout(guides = 'collect',
              heights = c(2,1))

p_regional_dcant_bias

ggsave(plot = p_regional_dcant_bias,
       path = "output/publication",
       filename = "regional_dcant.png",
       height = 5,
       width = 10)

rm(p_regional_bias, p_regional_dcant, p_regional_dcant_bias)

```

### Mean bias

```{r ensemble_mean_bias}

dcant_budget_basin_AIP_ensemble_bias <- full_join(
  dcant_budget_basin_AIP_ensemble %>%
    filter(data_source == "mod") %>% 
    select(basin_AIP, period, dcant_mean, dcant_sd),
  dcant_budget_basin_AIP_all %>%
    filter(data_source == "mod_truth",
           MLR_basins == "2") %>% 
    select(basin_AIP, period, dcant)
)

dcant_budget_basin_AIP_ensemble_bias <- dcant_budget_basin_AIP_ensemble_bias %>% 
  mutate(dcant_mean_bias = dcant_mean - dcant,
         dcant_mean_bias_rel = 100 * dcant_mean_bias / dcant)


dcant_budget_basin_AIP_ensemble_bias %>%
  ggplot(aes(period, dcant_mean_bias, col = basin_AIP)) +
  geom_hline(yintercept = 0) +
  geom_point()

dcant_budget_basin_AIP_ensemble_bias %>%
  ggplot(aes(period, dcant_mean_bias_rel, col = basin_AIP)) +
  geom_hline(yintercept = 0) +
  geom_point()


```

### SD vs bias

```{r ensemble_sd_vs_bias, fig.asp=0.5}

dcant_budget_basin_AIP_ensemble_bias %>% 
  ggplot(aes(dcant_mean_bias, dcant_sd, col=basin_AIP)) +
  geom_point() +
  facet_grid(. ~ period) +
  xlim(0, NA) +
  ylim(0, NA)

```


## Vertical patterns

### Absoulte values

```{r cases_absolute_depth, fig.asp=0.9}

dcant_budget_basin_AIP_all_depth %>%
  filter(
    MLR_basins %in% ensemble_MLR_basins,
    MLR_basins %in% ensemble_MLR_basins
  ) %>%
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~  ggplot(data = .x,
              aes(dcant, MLR_basins, fill = basin_AIP)) +
      geom_vline(xintercept = 0) +
      geom_col() +
      scale_fill_brewer(palette = "Dark2") +
      facet_grid(inv_depth ~ period) +
      labs(title = paste("data_source:", unique(.x$data_source)))
  )


```

### Biases

```{r cases_bias_depth, fig.asp=0.9}

dcant_budget_basin_AIP_bias_all_depth %>%
  filter(
    MLR_basins %in% ensemble_MLR_basins,
    MLR_basins %in% ensemble_MLR_basins
  ) %>%
  ggplot(aes(dcant_bias, MLR_basins, fill = basin_AIP)) +
  geom_vline(xintercept = 0) +
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

```

```{r cases_bias_rel_depth, fig.asp=0.9}

dcant_budget_basin_AIP_bias_all_depth %>%
  filter(
    MLR_basins %in% ensemble_MLR_basins,
    MLR_basins %in% ensemble_MLR_basins
  ) %>%
  ggplot(aes(dcant_bias_rel, MLR_basins, fill = basin_AIP)) +
  geom_vline(xintercept = 0) +
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

```

# Write ensemble members

```{r write_ensemble_members}

ensemble_MLR_basins %>% 
  write_rds("data/ensemble_members.rds")

```


