---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "1"
config <- "MLR_basins"

```



```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r find_removed_predictor, eval=FALSE}

all_predictors <- c("saltempaouoxygenphosphatenitratesilicate")

params_local_all <- params_local_all %>%
  mutate(MLR_predictors = str_remove_all(all_predictors,
                                         MLR_predictors))


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`


# Bias contribution


```{r cases_bias_global_contribution}

dcant_budget_global_bias_all %>%
  ggplot(aes(contribution, dcant_bias, fill=contribution)) +
  geom_hline(yintercept = 0) +
  scale_fill_brewer(palette = "Dark2") +
  labs(y = expression(atop(Delta * C[ant] ~ bias,
                               (PgC)))) +
  geom_col() +
  facet_grid({{config}} ~ period) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())

p_global_bias <-
  dcant_budget_global_bias_all %>%
  ggplot() +
  geom_hline(yintercept = global_bias_rel_max * c(-1, 1),
             linetype = 2) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = expression(Delta * C[ant] ~ bias ~ ("%")),
       title = "Model-based assesment") +
  theme(axis.title.x = element_blank()) +
  geom_point(aes(period, dcant_bias_rel, col = {{config}}),
  alpha = 0.7) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  facet_grid(. ~ contribution)

p_global_bias

dcant_budget_global_bias_all %>%
  group_by(period, contribution) %>%
  summarise(
    dcant_bias_sd = sd(dcant_bias),
    dcant_bias = mean(dcant_bias),
    dcant_bias_rel_sd = sd(dcant_bias_rel),
    dcant_bias_rel = mean(dcant_bias_rel)
  ) %>%
  ungroup() %>%
  kable() %>%
  kable_styling() %>%
  scroll_box(height = "300px")

```
