---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "c"
config <- "MLR_basins"

```



```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r find_removed_predictor, eval=FALSE}

all_predictors <- c("saltempaouoxygenphosphatenitratesilicate")

params_local_all <- params_local_all %>%
  mutate(MLR_predictors = str_remove_all(all_predictors,
                                         MLR_predictors))


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`



# Drift and bias

```{r read_files_global_dissic, include=FALSE}


for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join dissic files
  
  dcant_budget_global_dissic <-
    read_csv(paste(path_version_data,
                   "dcant_budget_global_dissic.csv",
                   sep = ""))
  
  
  dcant_budget_global_dissic <- dcant_budget_global_dissic %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  if (exists("dcant_budget_global_all_dissic")) {
    dcant_budget_global_all_dissic <-
      bind_rows(dcant_budget_global_all_dissic,
                dcant_budget_global_dissic)
  }
  
  if (!exists("dcant_budget_global_all_dissic")) {
    dcant_budget_global_all_dissic <- dcant_budget_global_dissic
  }
  
  # load and join global bias files
  
  dcant_budget_global_bias_decomposition <-
    read_csv(paste(
      path_version_data,
      "dcant_budget_global_bias_decomposition.csv",
      sep = ""
    ))
  
  
  dcant_budget_global_bias_decomposition <-
    dcant_budget_global_bias_decomposition %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  if (exists("dcant_budget_global_bias_all_decomposition")) {
    dcant_budget_global_bias_all_decomposition <-
      bind_rows(
        dcant_budget_global_bias_all_decomposition,
        dcant_budget_global_bias_decomposition
      )
  }
  
  if (!exists("dcant_budget_global_bias_all_decomposition")) {
    dcant_budget_global_bias_all_decomposition <-
      dcant_budget_global_bias_decomposition
  }
  
  
  # load and join basin_AIP bias files
  
  dcant_budget_basin_AIP_bias_decomposition <-
    read_csv(
      paste(
        path_version_data,
        "dcant_budget_basin_AIP_bias_decomposition.csv",
        sep = ""
      )
    )
  
  
  dcant_budget_basin_AIP_bias_decomposition <-
    dcant_budget_basin_AIP_bias_decomposition %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  if (exists("dcant_budget_basin_AIP_bias_all_decomposition")) {
    dcant_budget_basin_AIP_bias_all_decomposition <-
      bind_rows(
        dcant_budget_basin_AIP_bias_all_decomposition,
        dcant_budget_basin_AIP_bias_decomposition
      )
  }
  
  if (!exists("dcant_budget_basin_AIP_bias_all_decomposition")) {
    dcant_budget_basin_AIP_bias_all_decomposition <-
      dcant_budget_basin_AIP_bias_decomposition
  }
  
  # load and join 5 basins bias files
  
  dcant_budget_basin_MLR_bias_decomposition <-
    read_csv(
      paste(
        path_version_data,
        "dcant_budget_basin_MLR_bias_decomposition.csv",
        sep = ""
      )
    )
  
  
  dcant_budget_basin_MLR_bias_decomposition <-
    dcant_budget_basin_MLR_bias_decomposition %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  if (exists("dcant_budget_basin_MLR_bias_all_decomposition")) {
    dcant_budget_basin_MLR_bias_all_decomposition <-
      bind_rows(
        dcant_budget_basin_MLR_bias_all_decomposition,
        dcant_budget_basin_MLR_bias_decomposition
      )
  }
  
  if (!exists("dcant_budget_basin_MLR_bias_all_decomposition")) {
    dcant_budget_basin_MLR_bias_all_decomposition <-
      dcant_budget_basin_MLR_bias_decomposition
  }
  
}

rm(dcant_budget_global_dissic,
   dcant_budget_global_bias_decomposition,
   dcant_budget_basin_AIP_bias_decomposition,
   dcant_budget_basin_MLR_bias_decomposition)

dcant_budget_global_all_dissic <-
  full_join(dcant_budget_global_all_dissic,
            params_local_all)

dcant_budget_global_bias_all_decomposition <-
  full_join(dcant_budget_global_bias_all_decomposition,
            params_local_all)

dcant_budget_basin_AIP_bias_all_decomposition <-
  full_join(dcant_budget_basin_AIP_bias_all_decomposition,
            params_local_all)

dcant_budget_basin_MLR_bias_all_decomposition <-
  full_join(dcant_budget_basin_MLR_bias_all_decomposition,
            params_local_all)



```

```{r drift_bias_plots}

dcant_budget_global_all_dissic %>%
  filter(estimate == "dcant") %>%
  ggplot(aes(inv_depth, value, col = !!sym(config))) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2") +
  geom_point() +
  geom_path() +
  labs(y = "DIC change (PgC)") +
  facet_grid(data_source ~ period, scales = "free_y")


dcant_budget_global_bias_all_decomposition <-
  dcant_budget_global_bias_all_decomposition %>%
  filter(estimate == "dcant") %>%
  select(inv_depth, dcant_bias, contribution, !!sym(config), period) %>%
  pivot_wider(names_from = contribution,
              values_from = dcant_bias)

dcant_budget_global_bias_all_decomposition <-
  full_join(
    dcant_budget_global_bias_all_decomposition,
    dcant_budget_global_bias_all_depth %>%
      select(inv_depth, !!sym(config), period, mod_truth)
  )



dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(`dcant offset`, `delta C* - mod_truth`, col = !!sym(config))) +
  geom_vline(xintercept = 0, col = "grey50") +
  geom_hline(yintercept = 0, col = "grey50") +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(`dcant offset`, `C* prediction error`, col = !!sym(config))) +
  geom_vline(xintercept = 0, col = "grey50") +
  geom_hline(yintercept = 0, col = "grey50") +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(
    `dcant offset`,
    `C* prediction error` + `delta C* - mod_truth`,
    col = !!sym(config)
  )) +
  geom_vline(xintercept = 0, col = "grey50") +
  geom_hline(yintercept = 0, col = "grey50") +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(`dcant offset`, `C* drift`, col = !!sym(config))) +
  geom_vline(xintercept = 0, col = "grey50") +
  geom_hline(yintercept = 0, col = "grey50") +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(
    `dcant offset` - `C* drift`,
    `C* prediction error`,
    col = !!sym(config)
  )) +
  geom_vline(xintercept = 0, col = "grey50") +
  geom_hline(yintercept = 0, col = "grey50") +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(inv_depth ~ period)


dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(
    x = period,
    fill = !!sym(config),
    col = !!sym(config)
  )) +
  geom_hline(yintercept = 0) +
  geom_point(
    aes(y = `dcant offset`, shape = "dcant offset"),
    position = position_nudge(x = -0.05),
    alpha = 0.5
  ) +
  geom_point(
    aes(y = `dcant offset` - `C* drift`, shape = "dcant offset - C* drift"),
    position = position_nudge(x = 0.05),
    alpha = 0.5
  ) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21,23)) +
  facet_grid(inv_depth ~ .)

dcant_budget_global_bias_all_decomposition <-
  dcant_budget_global_bias_all_decomposition %>%
  mutate(
    `dcant offset rel` = 100 * `dcant offset` / mod_truth,
    `dcant offset rel corr` = 100 * (`dcant offset` - `C* drift`) / mod_truth,
    `C* prediction error rel` = 100 * (`C* prediction error`) / mod_truth
  )

dcant_budget_global_bias_all_decomposition %>%
  ggplot(aes(
    x = period,
    fill = !!sym(config),
    col = !!sym(config)
  )) +
  geom_hline(yintercept = 0) +
  geom_point(
    aes(y = `dcant offset rel`, shape = "dcant offset"),
    position = position_nudge(x = -0.05),
    alpha = 0.5
  ) +
  geom_point(
    aes(y = `dcant offset rel corr`, shape = "dcant offset - C* drift"),
    position = position_nudge(x = 0.05),
    alpha = 0.5
  ) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21,23)) +
  facet_grid(inv_depth ~ .)

dcant_budget_global_bias_all_decomposition <-
  dcant_budget_global_bias_all_decomposition %>%
  pivot_longer(-c(inv_depth:period),
               names_to = "estimate",
               values_to = "value")


dcant_budget_global_bias_all_decomposition %>%
  group_by(inv_depth, estimate) %>%
  summarise(mean = mean(value),
            sd = sd(value)) %>%
  ungroup() %>%
  kable() %>%
  kable_styling() %>%
  scroll_box(height = "300px")

dcant_budget_global_bias_all_decomposition %>%
  group_by(inv_depth, estimate, period) %>%
  summarise(mean = mean(value),
            sd = sd(value)) %>%
  ungroup() %>%
  kable() %>%
  kable_styling() %>%
  scroll_box(height = "300px")



```

