---
title: "Column inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(patchwork)
```


# Read files

```{r define_Version_IDs}

# identify required version IDs

Version_IDs <-
  list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
             pattern = "v_G0")


```


```{r read_files}


for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_inv <-
    read_csv(paste(path_version_data,
                   "dcant_inv.csv",
                   sep = ""))
  
  dcant_inv_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_inv_mod_truth.csv",
                   sep = "")) %>%
    filter(method == "total") %>%
    select(-method)
  
  dcant_inv_bias <-
    read_csv(paste(path_version_data,
                   "dcant_inv_bias.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_inv <- bind_rows(dcant_inv,
                         dcant_inv_mod_truth) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lat_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lat_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lon_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lon_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  
  if (exists("dcant_inv_all")) {
    dcant_inv_all <- bind_rows(dcant_inv_all, dcant_inv)
  }
  
  if (!exists("dcant_inv_all")) {
    dcant_inv_all <- dcant_inv
  }
  
  if (exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- bind_rows(dcant_inv_bias_all, dcant_inv_bias)
  }
  
  if (!exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- dcant_inv_bias
  }
  
  if (exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- bind_rows(dcant_budget_lat_grid_all, dcant_budget_lat_grid)
  }
  
  if (!exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- dcant_budget_lat_grid
  }
  
  if (exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- bind_rows(dcant_budget_lon_grid_all, dcant_budget_lon_grid)
  }
  
  if (!exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- dcant_budget_lon_grid
  }

  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(dcant_inv,
   dcant_inv_bias,
   dcant_inv_mod_truth,
   dcant_budget_lat_grid,
   dcant_budget_lon_grid,
   params_local,
   tref)

# params_local_all <-
#   params_local_all %>%
#   mutate(period = factor(period, c("1994 - 2004", "2004 - 2014", "1994 - 2014")))

dcant_inv_all <- full_join(dcant_inv_all,
                           params_local_all)

dcant_inv_bias_all <- full_join(dcant_inv_bias_all,
                                params_local_all)


dcant_budget_lat_grid_all <- full_join(dcant_budget_lat_grid_all,
                                       params_local_all)

dcant_budget_lon_grid_all <- full_join(dcant_budget_lon_grid_all,
                                       params_local_all)

```

```{r filter_standard_inventory_depth}

dcant_inv_all <- dcant_inv_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

```


```{r adapt_format}

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(method == "total")

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(method == "total")


```


```{r read_Gruber_2019_inventories}

dcant_inv_all_G19 <- read_csv(paste0(path_preprocessing,
                             "G19_dcant_inv_all.csv"))

```


# Individual cases

## Absoulte values

```{r harmonize_join_G19_M21}

dcant_inv_join <- bind_rows(
  dcant_inv_all_G19 %>%
    filter(Version_ID %in% c("01", "04", "05", "07")) %>%
    mutate(
      MLR_basins = recode(
        Version_ID,
        "01" = "2",
        "04" = "SO_AIP",
        "05" = "2+1",
        "07" = "5"
      )
    ) %>%
    select(lon, lat, dcant = dcant_pos, MLR_basins) %>% 
    mutate(source = "Gruber et al. (2019)"),
  dcant_inv_all %>%
    filter(data_source %in% c("obs")) %>%
    select(lon, lat, dcant, MLR_basins) %>% 
    mutate(source = "This study")
)

dcant_inv_join <- dcant_inv_join %>% 
  mutate(dcant = dcant * 10 / 13)

```


```{r cases_absolute, fig.asp=1.5}

dcant_inv_join %>%
  p_map_cant_inv(var = "dcant") +
  facet_grid(MLR_basins ~ source) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())


```

```{r plot_only_2_5}
library(ggtext)

dcant_inv_join <- 
dcant_inv_join %>% 
  filter(MLR_basins %in% c("2", "5"))


dcant_inv_join %>%
  p_map_cant_inv(var = "dcant",
                 title_text = NULL) +
  facet_grid(source ~ MLR_basins) +
  theme(axis.text.x = element_blank()) 

# legend_title <- expression(atop(Delta * C["ant"],
#                                 (mol ~ m ^ {
#                                   -2
#                                 } ~ dec ^ {
#                                   -1
#                                 })))
legend_title <- "ΔC<sub>ant</sub> column inventory<br>(mol m<sup>-2</sup> dec<sup>-1</sup>)"

p_CI_absolute <- 
  p_map_mdim_robinson(
    df = dcant_inv_join,
    var = "dcant",
    dim_row = "source",
    dim_col = "MLR_basins",
    legend_title = legend_title
  )

dcant_inv_join_offset <- dcant_inv_join %>% 
  arrange(source) %>% 
  group_by(lon, lat, MLR_basins) %>% 
  mutate(dcant_offset = dcant - lag(dcant)) %>% 
  ungroup()
  


dcant_inv_join_offset  %>%
  p_map_cant_inv(
    var = "dcant_offset",
    title_text = NULL,
    subtitle_text = NULL,
    col = "bias"
  ) +
  facet_grid(. ~ MLR_basins)


# legend_title <- expression(atop(Delta * C["ant"] ~ offset,
#                                 (mol ~ m ^ {
#                                   -2
#                                 } ~ dec ^ {
#                                   -1
#                                 })))
legend_title <- "ΔC<sub>ant</sub> column inventory offset<br>(mol m<sup>-2</sup> dec<sup>-1</sup>)"

p_CI_delta <-
  p_map_mdim_robinson(
    df = dcant_inv_join_offset %>%
      filter(!is.na(dcant_offset)) %>%
      select(lon, lat, dcant_offset, MLR_basins),
    var = "dcant_offset",
    breaks = c(-Inf, seq(-8, 8, 2), Inf),
    dim_col = "MLR_basins",
    legend_title = legend_title,
    col = "divergent"
  )  

p_CI_absolute / p_CI_delta + 
  plot_layout(heights = c(2,1)) +
  plot_annotation(tag_levels = 'a')

ggsave(path = here::here("output/publication"),
       filename = "FigS_dcant_column_inventory_1994_2007_vs_Gruber_2019.png",
       height = 160,
       width = 190,
       units = "mm",
       dpi = 600,
       bg = "white")

```

