---
title: "Column inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "g"
config <- "MLR_basins"

```




```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r find_removed_predictor, eval=FALSE}

all_predictors <- c("saltempaouoxygenphosphatenitratesilicate")

params_local_all <- params_local_all %>%
  mutate(MLR_predictors = str_remove_all(all_predictors,
                                         MLR_predictors))


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`


```{r data_coverage, eval=FALSE}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
 
  
  GLODAP_grid_era  <-
  read_csv(paste(path_version_data,
                  "GLODAPv2.2020_clean_obs_grid_era.csv",
                  sep = ""))
 
  
  GLODAP_grid_era  <- GLODAP_grid_era %>% 
    mutate(Version_ID = i_Version_IDs)
  
 

  if (exists("GLODAP_grid_era_all")) {
    GLODAP_grid_era_all <- bind_rows(GLODAP_grid_era_all, GLODAP_grid_era)
  }
  
  if (!exists("GLODAP_grid_era_all")) {
    GLODAP_grid_era_all <- GLODAP_grid_era
  }


  GLODAP_grid_era_all %>%
  group_split(period) %>%
  # head(1) %>%
  map(
    ~ map +
      geom_tile(data = .x,
             aes(lon, lat)) +
      facet_grid(gap_filling ~ era) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )
  
  
  GLODAP_grid_era_all <- full_join(GLODAP_grid_era_all,
                                params_local_all)
  
  
   
}

```

