---
title: "Column inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(patchwork)
```

# Uncertainty limit

```{r define_sd_uncertainty_limit}

sd_uncertainty_limit <- 4

```


# Read files

```{r define_Version_IDs}

# identify required version IDs

Version_IDs <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_2i")

# Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
#                             pattern = "v_20")
# 
# Version_IDs_3 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
#                             pattern = "v_30")
# 
# Version_IDs <- c(Version_IDs_1, Version_IDs_2, Version_IDs_3)

```


```{r read_files}


for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_inv <-
    read_csv(paste(path_version_data,
                   "dcant_inv.csv",
                   sep = ""))
  
  dcant_inv_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_inv_mod_truth.csv",
                   sep = "")) %>%
    filter(method == "total") %>%
    select(-method)
  
  dcant_inv_bias <-
    read_csv(paste(path_version_data,
                   "dcant_inv_bias.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_inv <- bind_rows(dcant_inv,
                         dcant_inv_mod_truth) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lat_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lat_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lon_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lon_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  
  if (exists("dcant_inv_all")) {
    dcant_inv_all <- bind_rows(dcant_inv_all, dcant_inv)
  }
  
  if (!exists("dcant_inv_all")) {
    dcant_inv_all <- dcant_inv
  }
  
  if (exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- bind_rows(dcant_inv_bias_all, dcant_inv_bias)
  }
  
  if (!exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- dcant_inv_bias
  }
  
  if (exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- bind_rows(dcant_budget_lat_grid_all, dcant_budget_lat_grid)
  }
  
  if (!exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- dcant_budget_lat_grid
  }
  
  if (exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- bind_rows(dcant_budget_lon_grid_all, dcant_budget_lon_grid)
  }
  
  if (!exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- dcant_budget_lon_grid
  }

  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(dcant_inv,
   dcant_inv_bias,
   dcant_inv_mod_truth,
   dcant_budget_lat_grid,
   dcant_budget_lon_grid,
   params_local,
   tref)

params_local_all <-
  params_local_all %>%
  mutate(period = factor(period, c("1994 - 2004", "2004 - 2014", "1994 - 2014")))

dcant_inv_all <- full_join(dcant_inv_all,
                           params_local_all)

dcant_inv_bias_all <- full_join(dcant_inv_bias_all,
                                params_local_all)


dcant_budget_lat_grid_all <- full_join(dcant_budget_lat_grid_all,
                                       params_local_all)

dcant_budget_lon_grid_all <- full_join(dcant_budget_lon_grid_all,
                                       params_local_all)

```

```{r filter_standard_inventory_depth}

dcant_inv_all <- dcant_inv_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

```


```{r adapt_format}

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(period != "1994 - 2014",
         method == "total")

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(period != "1994 - 2014",
         method == "total")


```


# Label test

```{r label_test_case}

dcant_inv_all <- dcant_inv_all %>%
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_inv_bias_all <- dcant_inv_bias_all %>%
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>%
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all  %>%
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )


```



# Individual cases

## Absoulte values

```{r cases_absolute, fig.asp=1.2}

dcant_inv_all %>%
  filter(data_source != "mod_truth") %>%
  p_map_cant_inv(var = "dcant") +
  facet_grid(label ~ data_source) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())


```

## Biases

```{r cases_bias, fig.asp=1.2}


dcant_inv_bias_all %>%
  p_map_cant_inv(var = "dcant_bias",
                 col = "bias",
                 subtitle_text = "data_source: mod - mod_truth") +
  facet_grid(label ~ period)


```

### Density distribution

```{r bias_density_distribution, fig.asp=1}

dcant_inv_bias_all %>%
  ggplot(aes(dcant_bias, col = label)) +
  scale_color_brewer(palette = "Dark2") +
  geom_vline(xintercept = 0) +
  geom_density() +
  facet_grid(period ~.) +
  coord_cartesian(xlim = c(-10, 10))

```


## Lat grid budgets

```{r lat_grid_budget_all, fig.asp=2}

dcant_budget_lat_grid_all %>%
  ggplot(aes(lat_grid, dcant, fill = label)) +
  geom_hline(yintercept = 0) +
  geom_col(position = "dodge") +
  coord_flip() +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(basin_AIP ~ data_source)

```

## Lon grid budgets

```{r lon_grid_budget_all}

dcant_budget_lon_grid_all %>%
  group_split(data_source, period) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(lon_grid, dcant, fill = label)) +
      geom_col(position = "dodge") +
      scale_fill_brewer(palette = "Dark2") +
      labs(title = paste(
        "data_source:",
        unique(.x$data_source),
        "| period:",
        unique(.x$period)
      )) +
      facet_grid(basin_AIP ~ .)
  )

```




