---
title: "Zonal sections"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
```

# Uncertainty limit

```{r define_sd_uncertainty_limit}

sd_uncertainty_limit <- 1.5

```


# Read files


```{r define_Version_IDs}

# identify required version IDs

Version_IDs <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = "v_2i")

# Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
#                             pattern = "v_20")
# 
# Version_IDs_3 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
#                             pattern = "v_30")
# 
# Version_IDs <- c(Version_IDs_1, Version_IDs_2, Version_IDs_3)

```


```{r read_files}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  # load and join data files
  
  dcant_zonal <-
    read_csv(paste(path_version_data,
                   "dcant_zonal.csv",
                   sep = ""))
  
  dcant_zonal_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_mod_truth.csv",
                   sep = ""))
  
  dcant_zonal <- bind_rows(dcant_zonal,
                         dcant_zonal_mod_truth)
  
  dcant_profile <-
    read_csv(paste(path_version_data,
                   "dcant_profile.csv",
                   sep = ""))
  
  dcant_profile_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_profile_mod_truth.csv",
                   sep = ""))
  
  dcant_profile <- bind_rows(dcant_profile,
                             dcant_profile_mod_truth)
  
  dcant_budget_basin_AIP_layer <-
    read_csv(paste(path_version_data,
                   "dcant_budget_basin_AIP_layer.csv",
                   sep = ""))
  
  dcant_zonal_bias <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_bias.csv",
                   sep = ""))
  

  dcant_zonal <- dcant_zonal %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_profile <- dcant_profile %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_basin_AIP_layer <- dcant_budget_basin_AIP_layer %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_zonal_bias <- dcant_zonal_bias %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>% 
    mutate(median_year_1 = sort(tref$median_year)[1],
           median_year_2 = sort(tref$median_year)[2],
           duration = median_year_2 - median_year_1,
           period = paste(median_year_1, "-", median_year_2))
  
  if (exists("dcant_zonal_all")) {
    dcant_zonal_all <- bind_rows(dcant_zonal_all, dcant_zonal)
  }
  
  if (!exists("dcant_zonal_all")) {
    dcant_zonal_all <- dcant_zonal
  }

  if (exists("dcant_profile_all")) {
    dcant_profile_all <- bind_rows(dcant_profile_all, dcant_profile)
  }
  
  if (!exists("dcant_profile_all")) {
    dcant_profile_all <- dcant_profile
  }

  if (exists("dcant_budget_basin_AIP_layer_all")) {
    dcant_budget_basin_AIP_layer_all <-
      bind_rows(dcant_budget_basin_AIP_layer_all,
                dcant_budget_basin_AIP_layer)
  }
  
  if (!exists("dcant_budget_basin_AIP_layer_all")) {
    dcant_budget_basin_AIP_layer_all <- dcant_budget_basin_AIP_layer
  }

  if (exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- bind_rows(dcant_zonal_bias_all, dcant_zonal_bias)
  }
  
  if (!exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- dcant_zonal_bias
  }

  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(dcant_zonal, dcant_zonal_bias, dcant_zonal_mod_truth,
   dcant_budget_basin_AIP_layer,
   tref)

dcant_zonal_all <- full_join(dcant_zonal_all,
                           params_local_all)

dcant_profile_all <- full_join(dcant_profile_all,
                           params_local_all)

dcant_budget_basin_AIP_layer_all <-
  full_join(dcant_budget_basin_AIP_layer_all,
            params_local_all)

dcant_zonal_bias_all <- full_join(dcant_zonal_bias_all,
                                params_local_all)

```

# Label test

```{r label_test_case}

dcant_zonal_all <- dcant_zonal_all %>% 
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_profile_all <- dcant_profile_all %>% 
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_zonal_bias_all <- dcant_zonal_bias_all %>% 
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )

dcant_budget_basin_AIP_layer_all <- dcant_budget_basin_AIP_layer_all %>% 
  mutate(
    label = case_when(
      Version_ID == "v_2i01"	~ "no_O2",
      Version_ID == "v_2i02"	~ "IO_test_lat",
      Version_ID == "v_2i03"	~ "IO_test_lon",
      Version_ID == "v_2i04"	~ "reoccupation",
      Version_ID == "v_2i05"	~ "tco2_target",
      Version_ID == "v_2i06"	~ "adj_filter"
    )
  )


```





# Individual cases

## Absoulte values

```{r cases_absolute, fig.asp=1.2}

dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant",
      plot_slabs = "n",
      subtitle_text = paste(
        "basin:",
        unique(.x$basin_AIP)
      )
    ) +
      facet_grid(label ~ data_source)
  )


```

## Biases

```{r cases_bias, fig.asp=1.2}

dcant_zonal_bias_all %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_bias",
      col = "divergent",
      plot_slabs = "n",
      subtitle_text = paste("basin:",
        unique(.x$basin_AIP)
      )
    ) +
      facet_grid(label ~ period)
  )


```


### Density distribution

```{r bias_density_distribution, fig.asp=1}

dcant_zonal_bias_all %>%
  ggplot(aes(dcant_bias, col = label)) +
  scale_color_brewer(palette = "Dark2") +
  geom_vline(xintercept = 0) +
  geom_density() +
  facet_grid(period ~.) +
  coord_cartesian(xlim = c(-10, 10))

```


## Concentration profiles

### Data source

```{r profiles_per_data_source, fig.asp=1.5}

dcant_profile_all %>%
  group_split(period) %>%
  map(
    ~ ggplot(data = .x,
             aes(
               dcant, depth,
               col = data_source, fill = data_source
             )) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_ribbon(
        aes(xmin = dcant - dcant_sd,
            xmax = dcant + dcant_sd),
        alpha = 0.2,
        col = "transparent"
      ) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid(label ~ basin_AIP)
  )

```

### Basin separation

```{r profiles_per_MLR_basins, fig.asp=1}

dcant_profile_all %>%
  group_split(period) %>%
  map(
    ~ ggplot(data = .x,
             aes(
               dcant, depth,
               col = label, fill = label
             )) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid(data_source ~ basin_AIP)
  )

```

### Era

```{r profiles_per_period, fig.asp=0.5}

dcant_profile_all %>%
  arrange(depth) %>%
  filter(period != "1994 - 2014") %>%
  group_split(data_source) %>%
  map(
    ~ ggplot(
      data = .x,
      aes(
        dcant,
        depth,
        col = period,
        group = interaction(label, period)
      )
    ) +
      geom_hline(yintercept = params_global$inventory_depth_standard) +
      geom_vline(xintercept = 0) +
      geom_path() +
      scale_y_reverse() +
      labs(title = paste("data_source", unique(.x$data_source))) +
      facet_grid(. ~ basin_AIP)
  )

```

## Layer budgets

```{r layer_budget_per_data_source, fig.asp=1.5}

dcant_budget_basin_AIP_layer_all %>%
  filter(estimate == "dcant") %>% 
  mutate(dcant = value,
         inv_depth = fct_inorder(as.factor(inv_depth))) %>% 
  group_split(period) %>%
  # head(1) %>% 
  map(
    ~ ggplot(data = .x,
             aes(dcant, inv_depth,
                 fill = label)) +
      geom_vline(xintercept = 0) +
      geom_col(position = "dodge") +
      scale_y_discrete(limits = rev) +
      scale_fill_brewer(palette = "Dark2") +
      labs(title = paste("period", unique(.x$period))) +
      facet_grid(data_source ~ basin_AIP)
  )

```



