---
title: "Column inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "t"
config <- "MLR_target"

```




```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r find_removed_predictor, eval=FALSE}

all_predictors <- c("saltempaouoxygenphosphatenitratesilicate")

params_local_all <- params_local_all %>%
  mutate(MLR_predictors = str_remove_all(all_predictors,
                                         MLR_predictors))


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`


# Individual cases

## Absoulte values

```{r cases_absolute_divergent_color_scale, fig.asp=1.2}


dcant_inv_all %>%
  filter(data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_cant_inv(df = .x,
                     var = "dcant",
                     subtitle_text = paste("data_source:",
                                           unique(.x$data_source)),
                     col = "divergent") +
      facet_grid(MLR_target ~ period) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )


```

