---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "m"
config <- "MLR_basins"

```



```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r order_vif_max_levels, eval=FALSE}

params_local_all <- params_local_all %>%
  mutate(vif_max = fct_inorder(vif_max))

```


```{r join_data_and_meta_data, include=FALSE}


dcant_budget_global_all <- full_join(dcant_budget_global_all,
                                     params_local_all)

dcant_budget_global_bias_all <-
  full_join(dcant_budget_global_bias_all,
            params_local_all)


dcant_budget_basin_AIP_all <- full_join(dcant_budget_basin_AIP_all,
                                        params_local_all)

dcant_budget_basin_AIP_bias_all <-
  full_join(dcant_budget_basin_AIP_bias_all,
            params_local_all)



dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(MLR_basins == "5") %>% 
  select(-MLR_basins)

dcant_budget_basin_MLR_all <- full_join(dcant_budget_basin_MLR_all,
                                        params_local_all)

dcant_slab_budget_all <- full_join(dcant_slab_budget_all,
                                        params_local_all)

dcant_slab_budget_bias_all <-
  full_join(dcant_slab_budget_bias_all,
            params_local_all)


dcant_obs_budget_all <- full_join(dcant_obs_budget_all,
                             params_local_all)


```


```{r filter_standard_inventory_depth_global}

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

dcant_budget_global_all_depth <- dcant_budget_global_all

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
  filter(estimate == "dcant") %>%
  select(-c(estimate))

dcant_budget_global_bias_all_depth <- dcant_budget_global_bias_all

dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```


```{r filter_standard_inventory_depth_basins}

dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

dcant_budget_basin_AIP_all_depth <- dcant_budget_basin_AIP_all

dcant_budget_basin_AIP_all <- dcant_budget_basin_AIP_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias_all %>%
  filter(estimate == "dcant") %>% 
  select(-c(estimate))

dcant_budget_basin_AIP_bias_all_depth <- dcant_budget_basin_AIP_bias_all

dcant_budget_basin_AIP_bias_all <- dcant_budget_basin_AIP_bias_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```

```{r filter_standard_inventory_depth_basins_hemisphere}

dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

# dcant_budget_basin_MLR_all_depth <- dcant_budget_basin_MLR_all

dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

# dcant_budget_basin_MLR_bias_all <- dcant_budget_basin_MLR_bias_all %>%
#   filter(estimate == "dcant") %>% 
#   select(-c(estimate))
# 
# dcant_budget_basin_MLR_bias_all_depth <- dcant_budget_basin_MLR_bias_all
# 
# dcant_budget_basin_MLR_bias_all <- dcant_budget_basin_MLR_bias_all %>%
#   filter(inv_depth == params_global$inventory_depth_standard)

```

```{r load_libraries_specific, include = FALSE}
library(patchwork)
```

# Bias thresholds

```{r define_bias_threshold}

global_bias_rel_max <- 12.5
global_bias_rel_max
regional_bias_rel_max <- 30
regional_bias_rel_max

```

# Global

## Individual cases

### Absoulte values

```{r cases_absolute_global}

legend_title = expression(atop(Delta * C[ant],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

dcant_budget_global_all %>%
  ggplot(aes(tref1, dcant)) +
  geom_line() +
  geom_point() +
  facet_grid(. ~ data_source) +
  ylim(0,NA) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())


```


# Basins

## Individual cases

### Absoulte values

```{r cases_absolute, fig.asp=0.9}

dcant_budget_basin_AIP_all %>%
  ggplot(aes(tref1, dcant, col = basin_AIP)) +
  geom_line() +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(. ~ data_source) +
  ylim(0,NA) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

```

### Biases

```{r cases_bias, fig.asp=0.9}

dcant_budget_basin_AIP_bias_all %>%
  ggplot(aes(tref1, dcant_bias, col = basin_AIP)) +
  geom_hline(yintercept = 0) +
  geom_line() +
  geom_point()

```

## Slab budgets

### Absolute values

```{r slab_budgets, fig.asp=1}

dcant_slab_budget_all %>%
  filter(data_source == "obs") %>% 
  mutate(tref1 = as.factor(tref1)) %>% 
  ggplot(aes(tref1, dcant, fill = gamma_slab)) +
  geom_hline(yintercept = 0, col = "red") +
  geom_col() +
  scale_fill_scico_d(direction = -1) +
  facet_grid(basin_AIP ~ .)

```

### Bias

```{r slab_budgets_bias, fig.asp=1}

dcant_slab_budget_bias_all %>%
  group_by(period) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(gamma_slab, dcant_bias, fill = gamma_slab)) +
      geom_col() +
      coord_flip() +
      scale_x_discrete(limits = rev) +
      scale_fill_scico_d(direction = -1) +
      facet_grid(basin_AIP ~ .) +
      labs(title = paste("period:", unique(.x$period)))
    )


```

# Basins hemisphere

## Individual cases

### Absoulte values

```{r cases_absolute_basins_hemisphere, fig.asp=1.2}

dcant_budget_basin_MLR_all %>%
    mutate(
    basin = str_replace(basin, "_", ". "),
    basin = fct_relevel(
      basin,
      "N. Pacific",
      "S. Pacific",
      "N. Atlantic",
      "S. Atlantic",
      "Indian"
    )
  ) %>% 
  ggplot(aes(tref1, dcant)) +
  geom_line(aes(col = basin)) +
  geom_point(aes(fill = basin),
             shape = 21) +
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(. ~ data_source) +
  ylim(0,NA) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())

```



