---
title: "Budgets"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r define_parameters}

version_id_pattern <- "s"
config <- "gobm"

```



```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r remove_version_id}

params_local_all <- params_local_all %>%
  mutate(gobm = str_split(gobm, "_v2", simplify = TRUE)[,1])


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/budget_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`


```{r read_files_global_dissic}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_budget_global_dissic <-
    read_csv(paste(path_version_data,
                   "dcant_budget_global_dissic.csv",
                   sep = ""))
  
  dcant_budget_global_dissic <- dcant_budget_global_dissic %>%
    mutate(Version_ID = i_Version_IDs)
  
  
  if (exists("dcant_budget_global_all_dissic")) {
    dcant_budget_global_all_dissic <-
      bind_rows(dcant_budget_global_all_dissic, dcant_budget_global_dissic)
  }
  
  if (!exists("dcant_budget_global_all_dissic")) {
    dcant_budget_global_all_dissic <- dcant_budget_global_dissic
  }
   
}

rm(dcant_budget_global_dissic)



dcant_budget_global_all_dissic <-
  full_join(dcant_budget_global_all_dissic,
            params_local_all)


dcant_budget_global_all_dissic %>%
  filter(estimate == "dcant") %>%
  mutate(inv_depth = inv_depth) %>% 
  ggplot(aes(inv_depth, value, col = gobm)) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2") +
  geom_point() +
  geom_path() +
  facet_grid(data_source ~ period, scales = "free_y")


dcant_budget_global_bias_all_depth %>%
  ggplot(aes(period, dcant_bias, col = gobm)) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = expression(atop(Delta * C[ant] ~ bias,
                               (mu * mol ~ kg ^ {-1})))) +
  geom_point() +
  facet_grid(inv_depth ~ contribution)


dcant_budget_global_bias_all_depth %>%
  select(inv_depth, dcant_bias, contribution, gobm, period) %>%
  pivot_wider(names_from = contribution,
              values_from = dcant_bias) %>% 
  ggplot(aes(`dcant offset`, `delta C* - mod_truth`, col = gobm)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_depth %>%
  select(inv_depth, dcant_bias, contribution, gobm, period) %>%
  pivot_wider(names_from = contribution,
              values_from = dcant_bias) %>% 
  ggplot(aes(`dcant offset`, `C* prediction error`, col = gobm)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(inv_depth ~ period)

dcant_budget_global_bias_all_depth %>%
  select(inv_depth, dcant_bias, contribution, gobm, period) %>%
  pivot_wider(names_from = contribution,
              values_from = dcant_bias) %>% 
  ggplot(aes(`dcant offset`, `C* prediction error` + `delta C* - mod_truth`, col = gobm)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(inv_depth ~ period)



drift_bias <- full_join(
  dcant_budget_global_bias_all_depth %>%
    select(inv_depth, dcant_bias, contribution, gobm, period),
    # pivot_wider(names_from = contribution,
    #             values_from = dcant_bias),
  dcant_budget_global_all_dissic %>%
    filter(data_source == "B",
           estimate == "dcant") %>%
    select(inv_depth, drift = value, gobm, period)
)

drift_bias %>%
  filter(period == "1994 - 2014") %>% 
  ggplot(aes(dcant_bias, drift, col = gobm)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(contribution ~ inv_depth)

drift_bias %>%
  filter(inv_depth == 3000) %>% 
  ggplot(aes(dcant_bias, drift, col = gobm)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point() +
  facet_grid(contribution ~ period)



```







