---
title: "Column inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r define_parameters}

version_id_pattern <- "s"
config <- "gobm"
```



```{r source_read_data_child, include = FALSE}


read <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_read_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(read))`

```{r remove_version_id}

params_local_all <- params_local_all %>%
  mutate(gobm = str_split(gobm, "_v2", simplify = TRUE)[,1])


```

```{r source_plot_data_child, include = FALSE}


plot <-
  knitr::knit_expand(
    file = here::here("analysis/child/column_inventories_analysis_plot_data.Rmd"),
    version_id_pattern = version_id_pattern,
    config = config
  )


```

`r knitr::knit(text = unlist(plot))`


# Dissic changes



```{r read_files_dissic, include=FALSE}


for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_inv_dissic <-
    read_csv(paste(path_version_data,
                   "dcant_inv_dissic.csv",
                   sep = ""))
 
  dcant_inv_dissic <- dcant_inv_dissic %>%
    mutate(Version_ID = i_Version_IDs)
  
 
  if (exists("dcant_inv_all_dissic")) {
    dcant_inv_all_dissic <- bind_rows(dcant_inv_all_dissic, dcant_inv_dissic)
  }
  
  if (!exists("dcant_inv_all_dissic")) {
    dcant_inv_all_dissic <- dcant_inv_dissic
  }
  

  
}

rm(dcant_inv_dissic)



dcant_inv_all_dissic <- full_join(dcant_inv_all_dissic,
                                  params_local_all)

```

```{r dissic_change_maps}

dcant_inv_all_dissic %>%
  group_split(inv_depth, period) %>%
  # head(1) %>% 
  map(
    ~ p_map_cant_inv(
      df = .x,
      var = "dcant",
      col = "divergent",
      legend_title = "DIC change\n(PgC)",
      subtitle_text = paste0(
        "inv_depth : ", unique(.x$inv_depth),
        " | period : ", unique(.x$period)
      )
    ) +
      facet_grid(data_source ~ gobm)
  )
```


