---
title: "Materials for publication"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

path_version_data     <-
  paste(path_observations,
        "v_XXX",
        "/data/",
        sep = "")

```

```{r load_libraries_specific, include = FALSE}
library(sf)
library(rnaturalearth)
library(ggnewscale)
library(patchwork)
library(marelac)
```

# Data sources

Following Cant estimates are used:

- Zonal mean (basin, lat, depth)
- Inventories (lat, lon)

```{r read_files}

cant_inv <-
  read_csv(paste(path_version_data,
                 "cant_inv.csv",
                 sep = ""))

cant_inv_mod_truth <-
  read_csv(paste(path_version_data,
                 "cant_inv_mod_truth.csv",
                 sep = ""))

cant_inv <- bind_rows(cant_inv, cant_inv_mod_truth)


cant_zonal <-
  read_csv(paste(path_version_data,
                 "cant_zonal.csv",
                 sep = ""))

cant_zonal_mod_truth <-
  read_csv(paste(path_version_data,
                 "cant_zonal_mod_truth.csv",
                 sep = ""))

cant_zonal <- bind_rows(cant_zonal,
                        cant_zonal_mod_truth)




GLODAP_clean <-
  read_csv(paste(path_version_data,
                 "GLODAPv2.2020_clean.csv",
                 sep = ""))

GLODAP_preprocessed <-
  read_csv(
    paste(
      path_preprocessing_model,
      "GLODAPv2.2020_preprocessed_model_runA_both.csv",
      sep = ""
    )
  )

GLODAP_grid_dup <-
  read_csv(paste(path_version_data,
                  "GLODAPv2.2020_clean_obs_grid_duplicates.csv",
                  sep = ""))


tref <-
  read_csv(paste(path_version_data,
                 "tref.csv",
                 sep = ""))


```


```{r read_params_local, include = FALSE}
params_local <-
  read_rds(
    "/UP_home/jenmueller/Projects/emlr_cant/observations/emlr_obs_v_XXX/data/auxillary/params_local.rds"
  )
```


```{r filter_standard_inventory_depth}

cant_inv <- cant_inv %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```

# Observations

## Inventory map

```{r mask_and_shape_files}

# coastlines and worldmap

coastlines <- ne_coastline(scale = "small", returnclass = "sf")
coastlines_re <- ne_coastline(scale = "small", returnclass = "sf")
worldmap <- ne_countries(scale = "small", returnclass = "sf")
worldmap_re <- ne_countries(scale = "small", returnclass = "sf")

crs <- st_crs(coastlines)

st_geometry(worldmap_re) <- st_geometry(worldmap_re) + c(360, 0)
st_crs(worldmap_re) <- crs
worldmap <- rbind(worldmap, worldmap_re)
rm(worldmap_re)

st_geometry(coastlines_re) <- st_geometry(coastlines_re) + c(360, 0)
st_crs(coastlines_re) <- crs
coastlines <- rbind(coastlines, coastlines_re)
rm(coastlines_re)

# coastlines_buffer <- st_buffer(coastlines, dist = 1)
# coastlines_re_buffer <- st_buffer(coastlines_re, dist = 1)

# coastline_raster <- stars::st_rasterize(coastlines, options = "ALL_TOUCHED=TRUE") %>% 
#   as.tibble()


# unmapped regions shape files

for (i_file in list.files("data/iho_marginal_seas")) {
  iho <- st_read(paste0("data/iho_marginal_seas/", i_file, "/iho.shp"))
  
  if (exists("marine_polys")) {
    marine_polys <- rbind(marine_polys, iho)
  } else {
    marine_polys <- iho
  }
  
}

marine_polys_re <- marine_polys
st_geometry(marine_polys_re) <- st_geometry(marine_polys) + c(360, 0)

st_crs(marine_polys) <- crs
st_crs(marine_polys_re) <- crs

marine_polys <- rbind(marine_polys, marine_polys_re)
rm(marine_polys_re)

# plot(st_geometry(marine_polys))
# ggplot() +
#   geom_sf(data = st_geometry(marine_polys), fill = "white")

# marine_polys_simple <- st_simplify(marine_polys, dTolerance = 0.5)
# ggplot() +
#   geom_sf(data = marine_polys, fill = "red") +
#   geom_sf(data = marine_polys_simple, fill = "white")

black_sea <- st_read("data/black_sea/provinces.shp")
black_sea_re <- black_sea
st_geometry(black_sea_re) <- st_geometry(black_sea) + c(360, 0)
st_crs(black_sea) <- crs
st_crs(black_sea_re) <- crs
black_sea <- rbind(black_sea, black_sea_re)
rm(black_sea_re)

hudson_bay <- st_read("data/hudson_bay/lme.shp")
hudson_bay_re <- hudson_bay
st_geometry(hudson_bay_re) <- st_geometry(hudson_bay) + c(360, 0)
st_crs(hudson_bay) <- crs
st_crs(hudson_bay_re) <- crs
hudson_bay <- rbind(hudson_bay, hudson_bay_re)
rm(hudson_bay_re)

caspian_sea <- st_read("data/caspian_sea/seavox_v17.shp")
caspian_sea_re <- caspian_sea
st_geometry(caspian_sea_re) <- st_geometry(caspian_sea) + c(360, 0)
st_crs(caspian_sea) <- crs
st_crs(caspian_sea_re) <- crs
caspian_sea <- rbind(caspian_sea, caspian_sea_re)
rm(caspian_sea_re)

# ggplot() +
#   geom_sf(data = marine_polys, fill = "white") +
#   geom_sf(data = black_sea, fill = "white") +
#   geom_sf(data = caspian_sea, fill = "white") +
#   geom_sf(data = hudson_bay, fill = "white")

```



```{r cant_inv_map_obs}

set_breaks <- c(-Inf, seq(0, 12, 2), Inf)
color_land <- "grey80"
color_unmapped <- "grey90"

var_name <- expression(atop(Delta * C["ant"],
                            (mol ~ m ^ {
                              -2
                            })))

GLODAP_grid_both <- GLODAP_grid_dup %>%
  filter(duplicate == "no") %>% 
  distinct(lon, lat, era)


p_inv_map <- ggplot() +
  geom_contour_fill(
    data = cant_inv %>% filter(data_source == "obs"),
    aes(lon, lat, z = cant_inv, fill = stat(level)),
    breaks = set_breaks,
    na.fill = TRUE
  ) +
  scale_fill_viridis_d(option = "D", name = var_name,
                       guide = guide_colorsteps()) +
  new_scale_fill() +
  geom_tile(data = GLODAP_grid_both,
              aes(x = lon, y = lat, height = 0.7, width = 0.7, fill=era)) +
  scale_fill_manual(values = c("Deeppink4", "Deeppink"),
                    name = "Decade") +
  geom_sf(data = marine_polys, fill = color_unmapped, col="transparent") +
  geom_sf(data = black_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = caspian_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = hudson_bay, fill = "white", col="white") +
  geom_sf(data = worldmap,  fill = color_land, col="transparent") +
  geom_sf(data = coastlines, col = "black") +
  coord_sf(ylim = c(-77.5,64.5), xlim = c(20.5,379.5), expand = 0) +
  labs(title = expression("Column inventory (0 - 3000m) of the change in anthropogenic CO"[2]~
                            "from 2006 to 2014")) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.key = element_rect(colour = "black"))


ggsave(plot = p_inv_map,
       path = "output/publication",
       filename = "dCant_inventory_map.png",
       height = 4,
       width = 10)

```



## Data time series histogram

```{r time_series}

time_histo <- GLODAP_preprocessed %>% 
  filter(!is.na(tco2)) %>% 
  count(year)

p_time_histo <-
  ggplot() +
  geom_col(data = time_histo %>% filter(year < 2000),
           aes(year, n, fill = "era1"),
           col = "grey20") +
  geom_col(
    data = time_histo %>% filter(year >= 2000, year < 2010),
    aes(year, n, fill = "era2"),
    col = "grey20"
  ) +
  geom_col(data = time_histo %>% filter(year >= 2010),
           aes(year, n, fill = "era3"),
           col = "grey20") +
  scale_fill_manual(values = c("grey", "Deeppink4", "Deeppink"),
                    name = "Decade", guide = FALSE) +
  scale_x_continuous(breaks = seq(1900, 2100, 5)) +
  scale_y_continuous(limits = c(0, max(time_histo$n)+500)) +
  coord_cartesian(expand = 0) +
  labs(title = "GLODAPv2.2020 | Observations per year") +
  theme_bw() +
  theme(axis.title = element_blank(),
        panel.grid = element_blank())


p_time_histo


ggsave(plot = p_time_histo,
       path = "output/publication",
       filename = "time_histo.png",
       height = 2,
       width = 10)

```


## Spatial time coverage

```{r annual_coverage_maps}

time_histo <- GLODAP_preprocessed %>%
  filter(year >= 2000) %>%
  distinct(lat, lon, year)

p_coverage_maps <- 
map +
  geom_raster(data = time_histo, aes(lon, lat)) +
  facet_wrap( ~ year) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank()
  )

p_coverage_maps

ggsave(plot = p_coverage_maps,
       path = "output/publication",
       filename = "data_coverage_maps_by_year.png",
       height = 7,
       width = 16)

```


```{r post_2000_coverage_map}

time_histo <- GLODAP_preprocessed %>%
  filter(year >= 2000) %>%
  distinct(lat, lon, year)

GLODAP_grid_both <- GLODAP_grid_dup %>%
  filter(duplicate == "no") %>% 
  count(lon, lat) %>% 
  mutate(n = as.factor(n))

p_coverage_maps <-
  ggplot() +
  geom_raster(data = GLODAP_grid_both,
              aes(x = lon, y = lat, fill = n)) +
  scale_fill_brewer(palette = "Set1",
                    name = "Decades\noccupied",
                    direction = -1) +
  geom_sf(data = worldmap,  fill = color_land, col = "transparent") +
  geom_sf(data = coastlines, col = "black") +
  coord_sf(
    ylim = c(-77.5, 64.5),
    xlim = c(20.5, 379.5),
    expand = 0
  ) +
  labs(title = "GLODAPv2.2020 | Data coverage in the post-2000 era") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.key = element_rect(colour = "black"),
    panel.grid = element_blank()
  )

p_coverage_maps

ggsave(plot = p_coverage_maps,
       path = "output/publication",
       filename = "data_coverage_map_post_2000.png",
       height = 4,
       width = 10)

```


```{r data_duplication_coverage_map}

p_coverage_maps <-
  ggplot() +
  geom_raster(data = GLODAP_grid_dup,
              aes(x = lon, y = lat, fill = duplicate)) +
  scale_fill_brewer(palette = "Set1",
                    name = "Duplicated\ndata",
                    direction = -1) +
  geom_sf(data = worldmap,  fill = color_land, col = "transparent") +
  geom_sf(data = coastlines, col = "black") +
  coord_sf(
    ylim = c(-77.5, 64.5),
    xlim = c(20.5, 379.5),
    expand = 0
  ) +
  facet_wrap(~ era, ncol = 1) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.key = element_rect(colour = "black"),
    panel.grid = element_blank()
  )

p_coverage_maps

ggsave(plot = p_coverage_maps,
       path = "output/publication",
       filename = "data_coverage_map_duplicated_data.png",
       height = 6,
       width = 7)

```



```{r cant_inv_map_color_only, eval=FALSE}

color_land <- "white"
color_unmapped <- "white"

p_inv_map <- ggplot() +
  geom_contour_fill(
    data = cant_inv %>% filter(data_source == "obs"),
    aes(lon, lat, z = cant_inv, fill = stat(level)),
    breaks = set_breaks,
    na.fill = TRUE
  ) +
  scale_fill_viridis_d(option = "D", name = var_name,
                       guide = FALSE) +
  geom_sf(data = marine_polys, fill = color_unmapped, col="transparent") +
  geom_sf(data = black_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = caspian_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = hudson_bay, fill = "white", col="white") +
  geom_sf(data = worldmap,  fill = color_land, col="transparent") +
  geom_sf(data = coastlines, col = "white") +
  coord_sf(ylim = c(-77.5,64.5), xlim = c(20.5,379.5), expand = 0) +
  theme_void()


ggsave(plot = p_inv_map,
       path = "output/publication",
       filename = "dCant_inventory_map_color_only.png",
       height = 4,
       width = 10)

```

## Uptake rate comparison

```{r uptake_rates}

cant_inv_budget <- cant_inv %>% 
  mutate(surface_area = earth_surf(lat, lon),
         cant_inv_grid = cant_inv*surface_area,
         cant_pos_inv_grid = cant_pos_inv*surface_area) %>% 
  group_by(basin_AIP, data_source, inv_depth) %>% 
  summarise(cant_total = sum(cant_inv_grid)*12*1e-15,
            cant_total = round(cant_total,1),
            cant_pos_total = sum(cant_pos_inv_grid)*12*1e-15,
            cant_pos_total = round(cant_pos_total,1)) %>% 
  ungroup()

duration <- sort(tref$median_year)[2] - sort(tref$median_year)[1]

cant_inv_budget_obs <- cant_inv_budget %>% 
  filter(data_source == "obs",
         inv_depth == 3000) %>% 
  summarise(cant_uptake_rate = sum(cant_total)/duration) %>% 
  mutate(source = "Interior\nstorage",
         period = "This study",
         uncertainty = 0.3)

cant_inv_budget_lit <-
  bind_cols(
    cant_uptake_rate = c(2.37, 2.18 + 0.61),
    source = c("Ocean\nmodels", "Observed\nfluxes"),
    period = c("Global\nCarbon Budget", "Global\nCarbon Budget"),
    uncertainty = c(0.6, 0.6)
  )

cant_inv_budget_all <- bind_rows(
  cant_inv_budget_obs,
  cant_inv_budget_lit
)



p_budget <-
  cant_inv_budget_all %>%
  ggplot() +
  geom_col(aes(source, cant_uptake_rate),
           fill = "grey80",
           col = "grey20") +
  geom_errorbar(
    aes(
      x = source,
      ymin = cant_uptake_rate - uncertainty,
      ymax = cant_uptake_rate + uncertainty
    ),
    width = .2
  ) +
    geom_text(
    aes(
      x = source,
      y = 0.8,
      label = period,
      angle = 90
    )
  ) +
  scale_y_continuous(limits = c(
    0,
    max(
      cant_inv_budget_all$cant_uptake_rate +
        cant_inv_budget_all$uncertainty
    ) + 0.1
  ),
  expand = c(0, 0)) +
  labs(title = "Ocean carbon sink 2006 - 2014",
       y = expression(Average~rate ~ (PgC ~ yr ^ {-1}))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        panel.grid = element_blank())


p_budget

ggsave(plot = p_budget,
       path = "output/publication",
       filename = "uptake_rate_comparison.png",
       height = 3.5,
       width = 3.5)


```


## Zonal mean sections

```{r zonal_mean_sections_obs}

breaks <- c(-Inf, seq(0, 10, 1), Inf)
breaks_n <- length(breaks) - 1

legend_title = expression(atop(Delta * C[ant, pos],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

i_basin_AIP <- "Atlantic"
slab_breaks <- params_local$slabs_Atl
i_data_source <- "obs"

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean")) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)")


# combine surface and deep water section
section_combined_Atl <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Atl



i_basin_AIP <- "Pacific"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean")) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Pac <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Pac



i_basin_AIP <- "Indian"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm"))) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean")) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Ind <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Ind




section_combined <-
section_combined_Atl | section_combined_Pac | section_combined_Ind



ggsave(plot = section_combined,
       path = "output/publication",
       filename = "zonal_mean_section_obs.png",
       height = 4,
       width = 12)


```

# Synthetic data

## Inventory map

```{r cant_inv_map_mod}

set_breaks <- c(-Inf, seq(0, 12, 2), Inf)
color_land <- "grey80"
color_unmapped <- "grey90"

var_name <- expression(atop(Delta * C["ant"],
                            (mol ~ m ^ {
                              -2
                            })))


p_inv_map <- ggplot() +
  geom_contour_fill(
    data = cant_inv %>% filter(data_source == "mod"),
    aes(lon, lat, z = cant_inv, fill = stat(level)),
    breaks = set_breaks,
    na.fill = TRUE
  ) +
  scale_fill_viridis_d(option = "D", name = var_name,
                       guide = guide_colorsteps()) +
  new_scale_fill() +
  geom_tile(data = GLODAP_grid_both,
              aes(x = lon, y = lat, height = 0.7, width = 0.7, fill=n)) +
  scale_fill_manual(values = c("Deeppink4", "Deeppink"),
                    name = "Eras\noccupied") +
  geom_sf(data = marine_polys, fill = color_unmapped, col="transparent") +
  geom_sf(data = black_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = caspian_sea,  fill = color_unmapped, col="transparent") +
  geom_sf(data = hudson_bay, fill = "white", col="white") +
  geom_sf(data = worldmap,  fill = color_land, col="transparent") +
  geom_sf(data = coastlines, col = "black") +
  coord_sf(ylim = c(-77.5,64.5), xlim = c(20.5,379.5), expand = 0) +
  labs(title = expression("Column inventory (0 - 3000m) of the change in anthropogenic CO"[2]~
                            "from 2006 to 2014"),
       subtitle = "eMLR(C*) reconstruction") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.key = element_rect(colour = "black"))

# bias map

set_breaks <- c(-Inf, seq(-4, 4, 1), Inf)
var_name <- expression(atop(Delta * C["ant"]~bias,
                            (mol ~ m ^ {
                              -2
                            })))


cant_inv_bias <- cant_inv %>%
  filter(data_source %in% c("mod", "mod_truth")) %>%
  select(lat, lon, data_source, cant_inv) %>%
  pivot_wider(names_from = data_source,
              values_from = cant_inv) %>%
  mutate(cant_inv_bias = mod - mod_truth) %>% 
  drop_na()



p_inv_map_bias <- ggplot() +
  geom_contour_fill(
    data = cant_inv_bias,
    aes(lon, lat, z = cant_inv_bias, fill = stat(level)),
    breaks = set_breaks,
    na.fill = TRUE
  ) +
  scale_fill_brewer(
    palette = "RdBu",
    direction = -1,
    drop = FALSE,
    name = var_name,
    guide = guide_colorsteps(barheight = unit(5, "cm"))
  ) +
  geom_sf(data = marine_polys, fill = color_unmapped, col = "transparent") +
  geom_sf(data = black_sea,  fill = color_unmapped, col = "transparent") +
  geom_sf(data = caspian_sea,  fill = color_unmapped, col = "transparent") +
  geom_sf(data = hudson_bay, fill = "white", col = "white") +
  geom_sf(data = worldmap,  fill = color_land, col = "transparent") +
  geom_sf(data = coastlines, col = "black") +
  coord_sf(
    ylim = c(-77.5, 64.5),
    xlim = c(20.5, 379.5),
    expand = 0
  ) +
  labs(subtitle = "eMLR(C*) reconstruction - model truth")+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.key = element_rect(colour = "black")
  )

p_inv_map_mod <- 
p_inv_map / p_inv_map_bias

ggsave(plot = p_inv_map_mod,
       path = "output/publication",
       filename = "dCant_inventory_map_mod_bias.png",
       height = 7,
       width = 9)

```

## Budgets

```{r cant_budget_mod}

cant_inv_budget_mod <- cant_inv_budget %>%
  filter(
    inv_depth == params_global$inventory_depth_standard,
    data_source %in% c("mod", "mod_truth")
  ) %>%
  select(-c(cant_pos_total, inv_depth))
  

cant_inv_budget_mod %>%
  pivot_wider(names_from = data_source,
              values_from = cant_total) %>%
  mutate(abs_bias = mod - mod_truth,
         rel_bias = ((mod / mod_truth) - 1) * 100)

cant_inv_budget_mod %>%
  group_by(data_source) %>%
  summarise(cant_total = sum(cant_total)) %>%
  ungroup() %>%
  pivot_wider(names_from = data_source,
              values_from = cant_total) %>%
  mutate(abs_bias = mod - mod_truth,
         rel_bias = ((mod / mod_truth) - 1) * 100)

p_budget_comparison <-
  cant_inv_budget_mod %>%
  mutate(
    data_source = recode(data_source,
                         mod = "eMLR(C*)\nreconstruction",
                         mod_truth = "Model\ntruth")
  ) %>%
  ggplot(aes(data_source, cant_total, fill = basin_AIP)) +
  scale_fill_brewer(palette = "Greys", name = "Ocean basin",
                    direction = -1) +
  scale_y_continuous(limits = c(0, 18), expand = c(0, 0)) +
  labs(y = expression(Delta * C["ant"] ~ (PgC)),
       title = "Regionally integrated budgets") +
  geom_col(col = "grey20") +
  theme_bw() +
  theme(axis.title.x = element_blank())

p_budget_comparison

ggsave(plot = p_budget_comparison,
       path = "output/publication",
       filename = "budget_comparison.png",
       height = 3.5,
       width = 4)

```


## Zonal mean sections

### eMLR

```{r zonal_mean_sections_mod}

breaks <- c(-Inf, seq(0, 10, 1), Inf)
breaks_n <- length(breaks) - 1

legend_title = expression(atop(Delta * C[ant, pos],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

i_basin_AIP <- "Atlantic"
slab_breaks <- params_local$slabs_Atl
i_data_source <- "mod"

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean"))

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)")


# combine surface and deep water section
section_combined_Atl <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Atl



i_basin_AIP <- "Pacific"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )


# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean"))
# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Pac <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Pac



i_basin_AIP <- "Indian"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal %>%
  filter(basin_AIP == i_basin_AIP,
         data_source == i_data_source) %>%
  ggplot() +
  guides(fill = guide_colorsteps(barheight = unit(5, "cm"))) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_mean),
                      breaks = breaks) +
  scale_fill_viridis_d(name = legend_title) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "white") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)",
       title =paste(i_basin_AIP, "Ocean")) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Ind <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Ind




section_combined <-
section_combined_Atl | section_combined_Pac | section_combined_Ind

section_combined

```

### Bias

```{r zonal_mean_sections_bias}

breaks <- c(-Inf, seq(-6, 6, 2), Inf)
breaks_n <- length(breaks) - 1

legend_title = expression(atop(Delta * C[ant]~bias,
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

cant_zonal_bias <- cant_zonal %>%
  filter(data_source %in% c("mod", "mod_truth")) %>%
  select(lat, depth, basin_AIP, data_source, cant_mean) %>%
  pivot_wider(names_from = data_source,
              values_from = cant_mean) %>%
  mutate(cant_bias = mod - mod_truth)

cant_zonal_bias <- full_join(
  cant_zonal_bias,
  cant_zonal_mod_truth %>% select(lat, depth, basin_AIP, gamma_mean)
)


i_basin_AIP <- "Atlantic"
slab_breaks <- params_local$slabs_Atl

# plot base section
section <-
  cant_zonal_bias %>%
  filter(basin_AIP == i_basin_AIP) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_bias),
                      breaks = breaks) +
  scale_fill_brewer(
    palette = "RdBu",
    direction = -1,
    drop = FALSE,
    name = legend_title,
    guide = guide_colorsteps(barheight = unit(5, "cm"))
  ) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "black") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "black",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)")


# combine surface and deep water section
section_combined_Atl <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Atl



i_basin_AIP <- "Pacific"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal_bias %>%
  filter(basin_AIP == i_basin_AIP) %>%
  ggplot() +
  guides(fill = FALSE) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_bias),
                      breaks = breaks) +
    scale_fill_brewer(
    palette = "RdBu",
    direction = -1,
    drop = FALSE,
    name = legend_title,
    guide = guide_colorsteps(barheight = unit(4, "cm"))
  ) +
  geom_hline(yintercept = params_local$depth_min,
             col = "black",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "black") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "white",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Pac <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Pac



i_basin_AIP <- "Indian"
slab_breaks <- params_local$slabs_Ind_Pac

# plot base section
section <-
  cant_zonal_bias %>%
  filter(basin_AIP == i_basin_AIP) %>%
  ggplot() +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm"))) +
  scale_y_reverse() +
  scale_x_continuous(breaks = seq(-100, 100, 20),
                     limits = c(min(cant_zonal$lat), max(cant_zonal$lat))) +
  geom_contour_filled(aes(lat, depth, z = cant_bias),
                      breaks = breaks) +
    scale_fill_brewer(
    palette = "RdBu",
    direction = -1,
    drop = FALSE,
    name = legend_title,
    guide = guide_colorsteps(barheight = unit(4, "cm"))
  ) +
  geom_hline(yintercept = params_local$depth_min,
             col = "white",
             linetype = 2) +
  geom_contour(aes(lat, depth, z = gamma_mean),
               breaks = slab_breaks,
               col = "black") +
  geom_text_contour(
    aes(lat, depth, z = gamma_mean),
    breaks = slab_breaks,
    col = "black",
    skip = 2
  )

# cut surface water section
surface <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(500, 0)) +
  labs(y = "Depth (m)") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# cut deep water section
deep <-
  section +
  coord_cartesian(expand = 0,
                  ylim = c(params_global$inventory_depth_standard, 500)) +
  labs(x = expression(latitude ~ (degree * N)), y = "Depth (m)") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


# combine surface and deep water section
section_combined_Ind <-
  surface / deep +
  plot_layout(guides = "collect")

section_combined_Ind




section_combined_bias <-
section_combined_Atl | section_combined_Pac | section_combined_Ind

section_mod_bias <-
section_combined / section_combined_bias


ggsave(plot = section_mod_bias,
       path = "output/publication",
       filename = "zonal_mean_section_mod_bias.png",
       height = 7,
       width = 14)


```

