---
title: "Rarefication: Slab inventories"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
```

# Read files

```{r read_files}

# identify required version IDs

# Version_IDs <- list.files(
#   path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
#   pattern = "v_")[1:34]

Version_IDs_1 <- list.files(
  path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
  pattern = "v_12")

Version_IDs_2 <- list.files(
  path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
  pattern = "v_22")

Version_IDs <- c(Version_IDs_1, Version_IDs_2)
rm(Version_IDs_1, Version_IDs_2)

# Version_IDs <- Version_IDs[1:length(Version_IDs)-1]

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  # load and join data files
  
  dcant_slab <-
    read_csv(paste(path_version_data,
                   "dcant_slab.csv",
                   sep = ""))
  
  dcant_slab_bias <-
    read_csv(paste(path_version_data,
                   "dcant_slab_bias.csv",
                   sep = ""))
  
  dcant_slab <- dcant_slab %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_slab_bias <- dcant_slab_bias %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>% 
    mutate(median_year_1 = sort(tref$median_year)[1],
           median_year_2 = sort(tref$median_year)[2],
           duration = median_year_2 - median_year_1,
           period = paste(median_year_1, "-", median_year_2))
  
  if (exists("dcant_slab_all")) {
    dcant_slab_all <- bind_rows(dcant_slab_all, dcant_slab)
  }
  
  if (!exists("dcant_slab_all")) {
    dcant_slab_all <- dcant_slab
  }

  if (exists("dcant_slab_bias_all")) {
    dcant_slab_bias_all <- bind_rows(dcant_slab_bias_all, dcant_slab_bias)
  }
  
  if (!exists("dcant_slab_bias_all")) {
    dcant_slab_bias_all <- dcant_slab_bias
  }

  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(dcant_slab, dcant_slab_bias,
   params_local, tref)

dcant_slab_all <- full_join(dcant_slab_all,
                           params_local_all)

dcant_slab_bias_all <- full_join(dcant_slab_bias_all,
                                params_local_all)

```

# Individual cases

## Absoulte values

```{r cases_absolute, fig.asp=0.9}

dcant_slab_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(period, gamma_slab) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_dcant_slab(
      df = .x,
      var = "dcant",
      subtitle_text = paste("period:",
                            unique(.x$period),
                            "| gamma_slab:", .x$gamma_slab)
    ) +
      facet_grid(MLR_basins ~ data_source)
  )


```

## Biases

```{r cases_bias, fig.asp=0.9}

dcant_slab_bias_all %>%
  group_by(gamma_slab) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_dcant_slab(
      df = .x,
      var = "dcant_bias",
      col = "divergent",
      subtitle_text = paste("gamma_slab:", .x$gamma_slab)
    ) +
      facet_grid(MLR_basins ~ period)
  )

```

# Ensemble

```{r calc_ensemble_metrics}

dcant_slab_ensemble <- dcant_slab_all %>% 
  filter(data_source %in% c("mod", "obs")) %>% 
  group_by(lat, lon, data_source, period, gamma_slab) %>% 
  summarise(dcant_mean = mean(dcant),
            dcant_sd = sd(dcant),
            dcant_range = max(dcant)- min(dcant)) %>% 
  ungroup()


```

## Mean

```{r ensemble_mean, fig.asp=0.5}

dcant_slab_ensemble %>%
  group_by(gamma_slab) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_dcant_slab(
      df = .x,
      var = "dcant_mean",
      subtitle_text = paste("period:",
                            unique(.x$period),
                            "| gamma_slab:", .x$gamma_slab)
    ) +
      facet_grid(period ~ data_source)
  )


```

## Mean bias

```{r ensemble_mean_bias, fig.asp=3}

dcant_slab_ensemble_bias <- full_join(
  dcant_slab_ensemble %>%
    filter(data_source == "mod") %>% 
    select(lat, lon, period, gamma_slab, dcant_mean, dcant_sd),
  dcant_slab_all %>%
    filter(data_source == "mod_truth",
           MLR_basins == "2") %>% 
    select(lat, lon, period, gamma_slab, dcant)
)

dcant_slab_ensemble_bias <- dcant_slab_ensemble_bias %>% 
  mutate(dcant_mean_bias = dcant_mean - dcant)

dcant_slab_ensemble_bias %>%
  p_map_dcant_slab(var = "dcant_mean_bias",
                   col = "divergent",
                   subtitle_text = "Ensemble mean - mod_truth") +
  facet_grid(gamma_slab ~ period)

```


## Standard deviation

```{r ensemble_sd, fig.asp=0.5}


dcant_slab_ensemble %>%
  group_by(gamma_slab) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_dcant_slab(
      df = .x,
      var = "dcant_sd",
      subtitle_text = paste("Ensemble SD | gamma_slab:", .x$gamma_slab)
    ) +
  facet_grid(period ~ data_source)
  )

```


## SD vs bias

```{r ensemble_sd_vs_bias, fig.asp=2}

dcant_min <- -20
dcant_max <- 20
dcant_sd_max <- 10

dcant_slab_ensemble_bias %>%
  ggplot(aes(dcant_mean_bias, dcant_sd)) +
  scale_fill_viridis_c(trans = "log10") +
  geom_bin2d(binwidth = 1) +
  facet_grid(gamma_slab ~ period) +
  coord_cartesian(ylim = c(0, dcant_sd_max),
                  xlim = c(dcant_min, dcant_max))



dcant_slab_ensemble_bias %>%
  select(dcant_mean, dcant_mean_bias, period, gamma_slab) %>%
  pivot_longer(dcant_mean:dcant_mean_bias,
               names_to = "estimate",
               values_to = "value") %>%
  ggplot(aes(value, col = estimate, linetype = period)) +
  scale_color_brewer(palette = "Set1") +
  geom_density() +
  facet_grid(gamma_slab ~ .) +
  coord_cartesian(xlim = c(dcant_min, dcant_max))

# dcant_slab_ensemble %>% 
#   ggplot(aes(dcant_sd)) +
#   geom_histogram() +
#   facet_grid(data_source ~ period) +
#   coord_cartesian(ylim = c(0,50))

```

## Range

```{r ensemble_range, fig.asp=0.5, eval=FALSE}

p_map_cant_inv(
  df = dcant_slab_ensemble,
  var = "dcant_range",
  breaks = c(seq(0,8,0.8), Inf),
  subtitle_text = paste("Ensemble range")
) +
  facet_grid(period ~ data_source)


```

# Cases vs ensemble

## Offset from mean

```{r ensemble_deviation_from_mean}

dcant_slab_all <- full_join(
  dcant_slab_all %>% select(-dcant_sd),
  dcant_slab_ensemble)

dcant_slab_all <- dcant_slab_all %>% 
  mutate(dcant_offset = dcant - dcant_mean)

dcant_slab_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(data_source, gamma_slab) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_dcant_slab(
      df = .x,
      var = "dcant_offset",
      col = "divergent",
      subtitle_text = paste("gamma_slab:", .x$gamma_slab,
                            "| data_source:", .x$data_source)
    ) +
      facet_grid(MLR_basins ~ period)
  )


```



