---
title: "Results publication"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

# Libraries


```{r load_libraries_specific, include = FALSE}
library(patchwork)
library(ggalluvial)
```


# Read files

## Paths and Versions

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```


```{r define_Version_IDs}

version_id_pattern <- "103"

# identify required version IDs

Version_IDs_1 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_1", version_id_pattern))

Version_IDs_2 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_2", version_id_pattern))

Version_IDs_3 <- list.files(path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
                            pattern = paste0("v_3", version_id_pattern))

Version_IDs <- c(Version_IDs_1, Version_IDs_2, Version_IDs_3)

print(Version_IDs)

```

## Parameters

```{r read_parameters}



for (i_Version_IDs in Version_IDs) {
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    tref1 = params_local$tref1,
    tref2 = params_local$tref2
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>%
    mutate(
      median_year_1 = sort(tref$median_year)[1],
      median_year_2 = sort(tref$median_year)[2],
      duration = median_year_2 - median_year_1,
      period = paste(median_year_1, "-", median_year_2)
    )
  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(params_local,
   tref)

params_local_all <- params_local_all %>% 
  select(Version_ID, period)

```


## Budgets

```{r read_budget_files_global}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_budget_global <-
    read_csv(paste(path_version_data,
                   "dcant_budget_global.csv",
                   sep = ""))
  
  dcant_budget_global_mod_truth <-
    read_csv(paste(
      path_version_data,
      "dcant_budget_global_mod_truth.csv",
      sep = ""
    ))
  # 
  # dcant_budget_global_bias <-
  #   read_csv(paste(path_version_data,
  #                  "dcant_budget_global_bias.csv",
  #                  sep = ""))
  # 
  # lm_best_predictor_counts <-
  #   read_csv(paste(path_version_data,
  #                  "lm_best_predictor_counts.csv",
  #                  sep = ""))
  # 
  # lm_best_dcant <-
  #   read_csv(paste(path_version_data,
  #                  "lm_best_dcant.csv",
  #                  sep = ""))
  
  dcant_budget_global <- bind_rows(dcant_budget_global,
                                      dcant_budget_global_mod_truth)
  
  dcant_budget_global <- dcant_budget_global %>%
    mutate(Version_ID = i_Version_IDs)
  
  # dcant_budget_global_bias <- dcant_budget_global_bias %>%
  #   mutate(Version_ID = i_Version_IDs)
  # 
  # lm_best_predictor_counts <- lm_best_predictor_counts %>%
  #   mutate(Version_ID = i_Version_IDs)
  # 
  # lm_best_dcant <- lm_best_dcant %>%
  #   mutate(Version_ID = i_Version_IDs)

  if (exists("dcant_budget_global_all")) {
    dcant_budget_global_all <-
      bind_rows(dcant_budget_global_all, dcant_budget_global)
  }
  
  if (!exists("dcant_budget_global_all")) {
    dcant_budget_global_all <- dcant_budget_global
  }
  
  # if (exists("dcant_budget_global_bias_all")) {
  #   dcant_budget_global_bias_all <-
  #     bind_rows(dcant_budget_global_bias_all,
  #               dcant_budget_global_bias)
  # }
  # 
  # if (!exists("dcant_budget_global_bias_all")) {
  #   dcant_budget_global_bias_all <- dcant_budget_global_bias
  # }
  # 
  #   
  # if (exists("lm_best_predictor_counts_all")) {
  #   lm_best_predictor_counts_all <-
  #     bind_rows(lm_best_predictor_counts_all, lm_best_predictor_counts)
  # }
  # 
  # if (!exists("lm_best_predictor_counts_all")) {
  #   lm_best_predictor_counts_all <- lm_best_predictor_counts
  # }
  #   
  # if (exists("lm_best_dcant_all")) {
  #   lm_best_dcant_all <-
  #     bind_rows(lm_best_dcant_all, lm_best_dcant)
  # }
  # 
  # if (!exists("lm_best_dcant_all")) {
  #   lm_best_dcant_all <- lm_best_dcant
  # }
  # 
  # if (exists("params_local_all")) {
  #   params_local_all <- bind_rows(params_local_all, params_local)
  # }
  # 
  # if (!exists("params_local_all")) {
  #   params_local_all <- params_local
  # }
  # 
  
}

rm(
  dcant_budget_global,
  # dcant_budget_global_bias,
  dcant_budget_global_mod_truth
  # lm_best_predictor_counts,
  # lm_best_dcant
)

```


```{r read_budget_files_basins_hemisphere}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_budget_basin_MLR <-
    read_csv(paste(path_version_data,
                   "dcant_budget_basin_MLR.csv",
                   sep = ""))
  
  dcant_budget_basin_MLR_mod_truth <-
    read_csv(paste(
      path_version_data,
      "dcant_budget_basin_MLR_mod_truth.csv",
      sep = ""
    ))
  
    
  dcant_budget_basin_MLR <- bind_rows(dcant_budget_basin_MLR,
                                      dcant_budget_basin_MLR_mod_truth)
  
  dcant_budget_basin_MLR <- dcant_budget_basin_MLR %>%
    mutate(Version_ID = i_Version_IDs)
  

  if (exists("dcant_budget_basin_MLR_all")) {
    dcant_budget_basin_MLR_all <-
      bind_rows(dcant_budget_basin_MLR_all, dcant_budget_basin_MLR)
  }
  
  if (!exists("dcant_budget_basin_MLR_all")) {
    dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR
  }

}

rm(
  dcant_budget_basin_MLR,
  dcant_budget_basin_MLR_mod_truth
)


```

```{r join_budget_data_and_meta_data, include=FALSE}


dcant_budget_global_all <- full_join(dcant_budget_global_all,
                                     params_local_all)

# dcant_budget_global_bias_all <-
#   full_join(dcant_budget_global_bias_all,
#             params_local_all)
# 
# 
# dcant_budget_basin_AIP_all <- full_join(dcant_budget_basin_AIP_all,
#                                         params_local_all)
# 
# dcant_budget_basin_AIP_bias_all <-
#   full_join(dcant_budget_basin_AIP_bias_all,
#             params_local_all)


dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(MLR_basins == "5") %>% 
  select(-MLR_basins)

dcant_budget_basin_MLR_all <- full_join(dcant_budget_basin_MLR_all,
                                        params_local_all)

# dcant_slab_budget_all <- full_join(dcant_slab_budget_all,
#                                         params_local_all)
# 
# dcant_slab_budget_bias_all <-
#   full_join(dcant_slab_budget_bias_all,
#             params_local_all)
# 
# 
# dcant_obs_budget_all <- full_join(dcant_obs_budget_all,
#                              params_local_all)


```


```{r filter_standard_inventory_depth_global}

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

# dcant_budget_global_all_depth <- dcant_budget_global_all

dcant_budget_global_all <- dcant_budget_global_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

# dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
#   filter(estimate == "dcant") %>%
#   select(-c(estimate))

# dcant_budget_global_bias_all_depth <- dcant_budget_global_bias_all
# 
# dcant_budget_global_bias_all <- dcant_budget_global_bias_all %>%
#   filter(inv_depth == params_global$inventory_depth_standard)

```

```{r filter_standard_inventory_depth_basins_hemisphere}

dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(estimate == "dcant", 
         method == "total") %>% 
  select(-c(estimate, method)) %>% 
  rename(dcant = value)

dcant_budget_basin_MLR_all <- dcant_budget_basin_MLR_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```



## Inventories

```{r read_iventory_files}

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  path_version_data     <-
    paste(path_observations,
          i_Version_IDs,
          "/data/",
          sep = "")
  
  # load and join data files
  
  dcant_inv <-
    read_csv(paste(path_version_data,
                   "dcant_inv.csv",
                   sep = ""))
  
  dcant_inv_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_inv_mod_truth.csv",
                   sep = "")) %>%
    filter(method == "total") %>%
    select(-method)
  
  dcant_inv_bias <-
    read_csv(paste(path_version_data,
                   "dcant_inv_bias.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_inv <- bind_rows(dcant_inv,
                         dcant_inv_mod_truth) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lat_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lat_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_lon_grid <-
    read_csv(paste(path_version_data,
                   "dcant_budget_lon_grid.csv",
                   sep = "")) %>%
    mutate(Version_ID = i_Version_IDs)
  if (exists("dcant_inv_all")) {
    dcant_inv_all <- bind_rows(dcant_inv_all, dcant_inv)
  }
  
  if (!exists("dcant_inv_all")) {
    dcant_inv_all <- dcant_inv
  }
  
  if (exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- bind_rows(dcant_inv_bias_all, dcant_inv_bias)
  }
  
  if (!exists("dcant_inv_bias_all")) {
    dcant_inv_bias_all <- dcant_inv_bias
  }
  
  if (exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- bind_rows(dcant_budget_lat_grid_all, dcant_budget_lat_grid)
  }
  
  if (!exists("dcant_budget_lat_grid_all")) {
    dcant_budget_lat_grid_all <- dcant_budget_lat_grid
  }
  
  if (exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- bind_rows(dcant_budget_lon_grid_all, dcant_budget_lon_grid)
  }
  
  if (!exists("dcant_budget_lon_grid_all")) {
    dcant_budget_lon_grid_all <- dcant_budget_lon_grid
  }
}

rm(dcant_inv,
   dcant_inv_bias,
   dcant_inv_mod_truth,
   dcant_budget_lat_grid,
   dcant_budget_lon_grid)

```

```{r filter_standard_inventory_depth_inventory}

dcant_inv_all <- dcant_inv_all %>%
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>% 
  filter(inv_depth == params_global$inventory_depth_standard)

```

```{r r join_iventory_data_and_meta_data, include=FALSE}


dcant_inv_all <- full_join(dcant_inv_all,
                           params_local_all)

dcant_inv_bias_all <- full_join(dcant_inv_bias_all,
                                params_local_all)


dcant_budget_lat_grid_all <- full_join(dcant_budget_lat_grid_all,
                                       params_local_all)

dcant_budget_lon_grid_all <- full_join(dcant_budget_lon_grid_all,
                                       params_local_all)

```


```{r adapt_iventory_format}

dcant_budget_lat_grid_all <- dcant_budget_lat_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(period != "1994 - 2014",
         method == "total")

dcant_budget_lon_grid_all <- dcant_budget_lon_grid_all %>%
  pivot_wider(names_from = estimate,
              values_from = value) %>%
  filter(period != "1994 - 2014",
         method == "total")


```


## Zonal sections

```{r read_zonal_section_files}

for (i_Version_IDs in Version_IDs) {

  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  # load and join data files
  
  dcant_zonal <-
    read_csv(paste(path_version_data,
                   "dcant_zonal.csv",
                   sep = ""))
  
  dcant_zonal_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_mod_truth.csv",
                   sep = ""))
  
  dcant_zonal <- bind_rows(dcant_zonal,
                         dcant_zonal_mod_truth)
  
  dcant_profile <-
    read_csv(paste(path_version_data,
                   "dcant_profile.csv",
                   sep = ""))
  
  dcant_profile_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_profile_mod_truth.csv",
                   sep = ""))
  
  dcant_profile <- bind_rows(dcant_profile,
                             dcant_profile_mod_truth)
  
  dcant_budget_basin_AIP_layer <-
    read_csv(paste(path_version_data,
                   "dcant_budget_basin_AIP_layer.csv",
                   sep = ""))
  
  dcant_zonal_bias <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_bias.csv",
                   sep = ""))
  

  dcant_zonal <- dcant_zonal %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_profile <- dcant_profile %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_budget_basin_AIP_layer <- dcant_budget_basin_AIP_layer %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_zonal_bias <- dcant_zonal_bias %>% 
    mutate(Version_ID = i_Version_IDs)

  
  if (exists("dcant_zonal_all")) {
    dcant_zonal_all <- bind_rows(dcant_zonal_all, dcant_zonal)
  }
  
  if (!exists("dcant_zonal_all")) {
    dcant_zonal_all <- dcant_zonal
  }

  if (exists("dcant_profile_all")) {
    dcant_profile_all <- bind_rows(dcant_profile_all, dcant_profile)
  }
  
  if (!exists("dcant_profile_all")) {
    dcant_profile_all <- dcant_profile
  }

  if (exists("dcant_budget_basin_AIP_layer_all")) {
    dcant_budget_basin_AIP_layer_all <-
      bind_rows(dcant_budget_basin_AIP_layer_all,
                dcant_budget_basin_AIP_layer)
  }
  
  if (!exists("dcant_budget_basin_AIP_layer_all")) {
    dcant_budget_basin_AIP_layer_all <- dcant_budget_basin_AIP_layer
  }

  if (exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- bind_rows(dcant_zonal_bias_all, dcant_zonal_bias)
  }
  
  if (!exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- dcant_zonal_bias
  }

}

rm(dcant_zonal, dcant_zonal_bias, dcant_zonal_mod_truth,
   dcant_budget_basin_AIP_layer)

```

```{r r join_zonal_section_data_and_meta_data, include=FALSE}

dcant_zonal_all <- full_join(dcant_zonal_all,
                           params_local_all)

dcant_profile_all <- full_join(dcant_profile_all,
                           params_local_all)

dcant_budget_basin_AIP_layer_all <-
  full_join(dcant_budget_basin_AIP_layer_all,
            params_local_all)

dcant_zonal_bias_all <- full_join(dcant_zonal_bias_all,
                                params_local_all)

```

# Define labels

```{r define_legend_titles}

dcant_pgc_label <- expression(Delta * C["ant"]~(PgC))

```


# Inventory maps

## Absoulte values

### dcant - absolute

```{r invetory_maps_absolute, fig.asp=0.9}

dcant_inv_all %>%
  filter(data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_cant_inv(df = .x,
                     var = "dcant",
                     subtitle_text = paste("data_source:",
                                           unique(.x$data_source))) +
      facet_grid(period ~ .) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )


```

```{r invetory_maps_absolute_test_color_scales, fig.asp=0.5}

breaks <- c(-Inf, seq(0, 16, 2), Inf)

legend_title <- expression(atop(Delta * C["ant"],
                                (mol ~ m ^ {
                                  -2
                                })))

breaks_n <- length(breaks) - 1

dcant_inv_all_color_test <- dcant_inv_all %>%
  filter(data_source %in% c("obs"),
         period == "2004 - 2014") %>%
  mutate(dcant_int = cut(dcant,
                         breaks,
                         right = FALSE))

scico_continous_palettes <- c(
  "acton",
  "bamako",
  "batlow",
  "bilbao",
  "buda",
  "davos",
  "devon",
  "grayC",
  "hawaii",
  "imola",
  "lajolla",
  "lapaz",
  "nuuk",
  "oslo",
  "tokyo",
  "turku"
)


for (i_palette in scico_continous_palettes) {
  p_reg <- map +
    geom_tile(data = dcant_inv_all_color_test,
              aes(lon, lat, fill = dcant_int)) +
    scale_fill_scico_d(
      palette = i_palette,
      drop = FALSE,
      name = legend_title,
      guide = "none"
    ) +
    # guides(fill = guide_colorsteps(barheight = unit(3, "cm"))) +
    labs(title = i_palette)
  
  p_rev <- map +
    geom_tile(data = dcant_inv_all_color_test,
              aes(lon, lat, fill = dcant_int)) +
    scale_fill_scico_d(
      palette = i_palette,
      drop = FALSE,
      name = legend_title,
      direction = -1,
      guide = "none"
    ) +
    # guides(fill = guide_colorsteps(barheight = unit(3, "cm"))) +
    labs(title = paste(i_palette, "rev"))
  
  print(p_reg | p_rev)
  
}


# viridis_continous_palettes <- c(
#   "civides",
#   "magma",
#   "inferno",
#   "plasma"
# )
# 
# viridis::
# 
# for (i_palette in scico_continous_palettes) {
#   p_reg <- map +
#     geom_tile(data = dcant_inv_all_color_test,
#               aes(lon, lat, fill = dcant_int)) +
#     scale_fill_scico_d(
#       palette = i_palette,
#       drop = FALSE,
#       name = legend_title,
#       guide = "none"
#     ) +
#     # guides(fill = guide_colorsteps(barheight = unit(3, "cm"))) +
#     labs(title = i_palette)
#   
#   p_rev <- map +
#     geom_tile(data = dcant_inv_all_color_test,
#               aes(lon, lat, fill = dcant_int)) +
#     scale_fill_scico_d(
#       palette = i_palette,
#       drop = FALSE,
#       name = legend_title,
#       direction = -1,
#       guide = "none"
#     ) +
#     # guides(fill = guide_colorsteps(barheight = unit(3, "cm"))) +
#     labs(title = paste(i_palette, "rev"))
#   
#   print(p_reg | p_rev)
#   
# }


```

### dcant - absolute delta

```{r invetory_maps_absolute_delta}


dcant_inv_all %>%
  filter(data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  select(data_source, lon, lat, basin_AIP, period, dcant) %>% 
  pivot_wider(names_from = period,
              values_from = dcant) %>% 
  mutate(delta_dcant = `2004 - 2014` - `1994 - 2004`) %>% 
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_cant_inv(df = .x,
                     var = "delta_dcant",
                     subtitle_text = paste("data_source:",
                                           unique(.x$data_source)),
                     col = "divergent") +
      # facet_grid(period ~ .) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )


```

### dcant - absolute delta scaled

```{r invetory_maps_absolute_delta_scaled}

dcant_budget_scaling <- dcant_budget_global_all %>%
  filter(#data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  select(data_source, period, dcant) %>%
  pivot_wider(names_from = period,
              values_from = dcant) %>% 
  mutate(dcant_scaling = `2004 - 2014` / `1994 - 2004`) %>% 
  select(data_source, dcant_scaling)


left_join(dcant_inv_all,
          dcant_budget_scaling) %>%
  filter(#data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  select(data_source, lon, lat, basin_AIP, period, dcant, dcant_scaling) %>% 
  pivot_wider(names_from = period,
              values_from = dcant) %>% 
  mutate(delta_dcant = `2004 - 2014` - `1994 - 2004`*dcant_scaling) %>% 
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_cant_inv(df = .x,
                     var = "delta_dcant",
                     subtitle_text = paste("data_source:",
                                           unique(.x$data_source)),
                     col = "divergent") +
      # facet_grid(period ~ .) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )


```


### dcant pos - absolute

```{r cases_absolute_dcant_pos, fig.asp=0.9}


dcant_inv_all %>%
  filter(data_source %in% c("mod", "obs"),
         period != "1994 - 2014") %>%
  group_by(data_source) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_map_cant_inv(df = .x,
                     var = "dcant_pos",
                     subtitle_text = paste("data_source:",
                                           unique(.x$data_source))) +
      facet_grid(period ~ .) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank())
  )


```


# Zonal sections

```{r zonal_sections}

dcant_zonal_all %>%
  filter(data_source == "obs",
         period != "1994 - 2014",
         depth <= params_global$inventory_depth_standard) %>%
  p_section_zonal_continous_depth(var = "dcant",
                                  plot_slabs = "n",
                                  title_text = NULL) +
  facet_grid(basin_AIP ~ period)


```




# Budgets

## Basin & hemisphere

```{r budgets_basins_hemisphere, fig.asp=1.2}

dcant_budget_basin_MLR_all_plot <- dcant_budget_basin_MLR_all %>%
  filter(period != "1994 - 2014",
         data_source == "obs") %>%
  mutate(
    basin = str_replace(basin, "_", ". "),
        basin = fct_relevel(
      basin,
      "N. Pacific",
      "S. Pacific",
      "N. Atlantic",
      "S. Atlantic",
      "Indian"
    )
  )

```

```{r budgets_basins_hemisphere_alluvial_order_budget, fig.asp=0.9}

g1 <- dcant_budget_basin_MLR_all_plot %>%
  ggplot(aes(
    y = dcant,
    x = period,
    alluvium = basin,
    fill  = basin,
    stratum = basin
  )) +
  stat_alluvium(decreasing = FALSE) +
  stat_stratum(decreasing = FALSE) +
  stat_stratum(geom = "text",
               decreasing = FALSE,
               aes(label = paste(
                 round(after_stat(max-min),1)
                 # 100*round(after_stat(prop), 2), "%"
                 ))) +
  ggrepel::geom_label_repel(
    data = dcant_budget_basin_MLR_all_plot %>% filter(period == "2004 - 2014"),
    stat = "stratum",
    size = 4,
    nudge_x = .5,
    point.padding = 3,
    aes(fill = basin, label = basin),
    decreasing = FALSE
  )+
  scale_fill_brewer(palette = "Paired", guide = "none") +
  scale_y_continuous(limits = c(0, 32), expand = c(0, 0)) +
  labs(y = dcant_pgc_label) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  theme_classic()

newdat <- tibble(layer_data(g1))

change <- 
  newdat %>% 
  select(x, alluvium, count) %>% 
  pivot_wider(names_from = x,
              values_from = count) %>% 
  mutate(dcant_change = round(100*(`2` - `1`) / `1`)) %>% 
  select(alluvium, dcant_change)

coord <- newdat %>%
  filter(x == 2) %>% 
  select(x, y, alluvium)

new_layer <- full_join(
  change,
  coord
)

new_layer <- new_layer %>% 
  mutate(dcant_change = as.character(dcant_change),
         dcant_change = if_else(str_detect(dcant_change, "-"),
                                dcant_change,
                                paste0("+", dcant_change)),
         dcant_change = paste(dcant_change, "%"))

g1 +
  geom_text(data = new_layer,
            aes(
              x = x - 0.3,
              y = y,
              label = dcant_change
            ),
            inherit.aes = FALSE)


```


```{r budgets_basins_hemisphere_alluvial_order_basin, fig.asp=0.9}
g2 <- dcant_budget_basin_MLR_all_plot %>%
  ggplot(aes(
    y = dcant,
    x = period,
    alluvium = basin,
    fill  = basin,
    stratum = basin,
    label = basin
  )) +
  geom_alluvium() +
  geom_stratum() +
  stat_stratum(geom = "text",
               aes(label = paste(
                 round(after_stat(count),1)
                 # 100*round(after_stat(prop), 2), "%"
                 ))) +
  ggrepel::geom_label_repel(
    data = dcant_budget_basin_MLR_all_plot %>% filter(period == "2004 - 2014"),
    stat = "stratum",
    size = 4,
    nudge_x = .5,
    point.padding = 3,
    aes(fill = basin)
  )+
  scale_fill_brewer(palette = "Paired", guide = "none") +
  scale_color_brewer(palette = "Paired", guide = "none") +
  scale_y_continuous(limits = c(0, 32.5), expand = c(0, 0)) +
  guides(y = "none") +
  labs(title = dcant_pgc_label) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0.5))


newdat <- tibble(layer_data(g2))

change_basin <- 
  newdat %>% 
  select(x, alluvium, count) %>% 
  pivot_wider(names_from = x,
              values_from = count) %>% 
  mutate(dcant_change = round(100*(`2` - `1`) / `1`)) %>% 
  select(alluvium, dcant_change)

coord_basin <- newdat %>%
  filter(x == 2) %>% 
  select(x, y, alluvium)

new_layer_basin <- full_join(
  change_basin,
  coord_basin
)

new_layer_basin <- new_layer_basin %>% 
  mutate(dcant_change = as.character(dcant_change),
         dcant_change = if_else(str_detect(dcant_change, "-"),
                                dcant_change,
                                paste0("+", dcant_change)),
         dcant_change = paste(dcant_change, "%"))

new_layer_total <- 
  newdat %>% 
  select(x, alluvium, count) %>% 
  group_by(x) %>% 
  summarise(dcant_change = sum(count)) %>% 
  ungroup()

new_layer_total <- new_layer_total %>% 
  mutate(y = dcant_change,
         dcant_change = as.character(round(dcant_change,1)),
         dcant_change = paste("global:",dcant_change))

g2 +
  geom_text(data = new_layer_basin,
            aes(
              x = x - 0.3,
              y = y,
              label = dcant_change
            ),
            inherit.aes = FALSE) +
  geom_label(data = new_layer_total,
            aes(
              x = x,
              y = y + 1,
              label = dcant_change
            ),
            inherit.aes = FALSE)


```

