---
title: "tref definition: Zonal sections"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")


path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

```

```{r load_libraries_specific, include = FALSE}
```

# Read files

```{r read_files}

# identify required version IDs

Version_IDs_1 <- list.files(
  path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
  pattern = "v_10")[c(2,5)]

Version_IDs_2 <- list.files(
  path = "/nfs/kryo/work/jenmueller/emlr_cant/observations",
  pattern = "v_20")[c(2,5)]

Version_IDs <- c(Version_IDs_1, Version_IDs_2)
rm(Version_IDs_1, Version_IDs_2)

# Version_IDs <- Version_IDs[1:length(Version_IDs)-1]

for (i_Version_IDs in Version_IDs) {
  # i_Version_IDs <- Version_IDs[1]
  
  print(i_Version_IDs)
  
  path_version_data     <-
  paste(path_observations,
        i_Version_IDs,
        "/data/",
        sep = "")
  
  # load and join data files
  
  dcant_zonal <-
    read_csv(paste(path_version_data,
                   "dcant_zonal.csv",
                   sep = ""))
  
  dcant_zonal_mod_truth <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_mod_truth.csv",
                   sep = ""))
  
  dcant_zonal_bias <-
    read_csv(paste(path_version_data,
                   "dcant_zonal_bias.csv",
                   sep = ""))
  
  dcant_zonal <- bind_rows(dcant_zonal,
                         dcant_zonal_mod_truth)
  
  dcant_zonal <- dcant_zonal %>% 
    mutate(Version_ID = i_Version_IDs)
  
  dcant_zonal_bias <- dcant_zonal_bias %>% 
    mutate(Version_ID = i_Version_IDs)
  
  params_local <-
    read_rds(paste(path_version_data,
                   "params_local.rds",
                   sep = ""))
  
  params_local <- bind_cols(
    Version_ID = i_Version_IDs,
    MLR_basins = params_local$MLR_basins,
    era_start = str_c(params_local$era_start, collapse = "+"),
    era_end = str_c(params_local$era_end, collapse = "+"),
    tref1 = params_local$tref1,
    tref2 = params_local$tref2,
    gap_filling = params_local$gap_filling,
    rarefication = params_local$rarefication,
    rarefication_threshold = params_local$rarefication_threshold,
    MLR_predictors = str_c(params_local$MLR_predictors, collapse = "+"),
    vif_max = params_local$vif_max
  )
  
  tref <- read_csv(paste(path_version_data,
                         "tref.csv",
                         sep = ""))
  
  params_local <- params_local %>% 
    mutate(median_year_1 = sort(tref$median_year)[1],
           median_year_2 = sort(tref$median_year)[2],
           duration = median_year_2 - median_year_1,
           period = paste(median_year_1, "-", median_year_2))
  
  if (exists("dcant_zonal_all")) {
    dcant_zonal_all <- bind_rows(dcant_zonal_all, dcant_zonal)
  }
  
  if (!exists("dcant_zonal_all")) {
    dcant_zonal_all <- dcant_zonal
  }

  if (exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- bind_rows(dcant_zonal_bias_all, dcant_zonal_bias)
  }
  
  if (!exists("dcant_zonal_bias_all")) {
    dcant_zonal_bias_all <- dcant_zonal_bias
  }

  if (exists("params_local_all")) {
    params_local_all <- bind_rows(params_local_all, params_local)
  }
  
  if (!exists("params_local_all")) {
    params_local_all <- params_local
  }
  
  
}

rm(dcant_zonal, dcant_zonal_bias, dcant_zonal_mod_truth,
   tref)

params_local_all <- params_local_all %>% 
  mutate(tref_def = "manual",
         tref_def = if_else(is.na(tref1), "median", tref_def))

dcant_zonal_all <- full_join(dcant_zonal_all,
                             params_local_all)

dcant_zonal_bias_all <- full_join(dcant_zonal_bias_all,
                                  params_local_all)

```

# Raw results

## Absoulte values

```{r cases_absolute, fig.asp=1.2}


legend_title <- expression(atop(Delta * C[ant],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(basin_AIP, data_source) %>%
  group_split() %>%
  head(1) %>%
  map(
    ~ ggplot(data = .x) +
      geom_contour_filled(aes(lat, depth, z = dcant_mean),
                          breaks = c(-Inf, seq(-2,16,2), Inf)) +
      scale_fill_viridis_d(
        drop = FALSE,
        name = legend_title
      ) +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"),
                                     show.limits = TRUE)) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(100,500,seq(1000,5000,1000))) +
      # scale_y_reverse(breaks = c(100,500,seq(1000,5000,1000))) +
      scale_x_continuous(breaks = seq(-100, 100, 40),
                         limits = c(-80, 65)) +
      facet_grid(tref_def ~ era_start) +
      coord_cartesian(expand = 0) +
      labs(title = paste("data_source", unique(.x$data_source),
                         "| basin:", unique(.x$basin_AIP)))
  )


```

## Offset

```{r cases_bias, fig.asp=1.2}

dcant_zonal_all_offset <- dcant_zonal_all %>% 
  select(lat, depth, basin_AIP, data_source, era_start, tref_def, dcant_mean) %>% 
  pivot_wider(names_from = tref_def,
              values_from = dcant_mean) %>% 
  mutate(dcant_offset = manual - median)


dcant_zonal_all_offset %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x) +
      geom_contour_filled(aes(lat, depth, z = dcant_offset),
                          breaks = c(-Inf, seq(-2,2,0.25), Inf)) +
      scale_fill_scico_d(
        palette = "vik",
        drop = FALSE,
        name = legend_title
      ) +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"),
                                     show.limits = TRUE)) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(100,500,seq(1000,5000,1000))) +
      # scale_y_reverse(breaks = c(100,500,seq(1000,5000,1000))) +
      scale_x_continuous(breaks = seq(-100, 100, 40),
                         limits = c(-80, 65)) +
      facet_grid(data_source ~ era_start) +
      coord_cartesian(expand = 0) +
      labs(title = paste("basin:", unique(.x$basin_AIP)))
  )


```

# Scaled results

## Absoulte values

```{r cases_absolute_scaled, fig.asp=1.2}

dcant_zonal_all <- dcant_zonal_all %>% 
  mutate(dcant_mean = dcant_mean * 10 / duration)


legend_title <- expression(atop(Delta * C[ant],
                               (mu * mol ~ kg ^ {
                                 -1
                               })))

dcant_zonal_all %>%
  filter(data_source %in% c("mod", "obs")) %>%
  group_by(basin_AIP, data_source) %>%
  group_split() %>%
  head(1) %>%
  map(
    ~ ggplot(data = .x) +
      geom_contour_filled(aes(lat, depth, z = dcant_mean),
                          breaks = c(-Inf, seq(-2,16,2), Inf)) +
      scale_fill_viridis_d(
        drop = FALSE,
        name = legend_title
      ) +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"),
                                     show.limits = TRUE)) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(100,500,seq(1000,5000,1000))) +
      # scale_y_reverse(breaks = c(100,500,seq(1000,5000,1000))) +
      scale_x_continuous(breaks = seq(-100, 100, 40),
                         limits = c(-80, 65)) +
      facet_grid(tref_def ~ era_start) +
      coord_cartesian(expand = 0) +
      labs(title = paste("data_source", unique(.x$data_source),
                         "| basin:", unique(.x$basin_AIP)))
  )


```

## Offset

```{r cases_bias_scaled, fig.asp=1.2}

dcant_zonal_all_offset <- dcant_zonal_all %>% 
  select(lat, depth, basin_AIP, data_source, era_start, tref_def, dcant_mean) %>% 
  pivot_wider(names_from = tref_def,
              values_from = dcant_mean) %>% 
  mutate(dcant_offset = manual - median)


dcant_zonal_all_offset %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x) +
      geom_contour_filled(aes(lat, depth, z = dcant_offset),
                          breaks = c(-Inf, seq(-2,2,0.25), Inf)) +
      scale_fill_scico_d(
        palette = "vik",
        drop = FALSE,
        name = legend_title
      ) +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"),
                                     show.limits = TRUE)) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(100,500,seq(1000,5000,1000))) +
      # scale_y_reverse(breaks = c(100,500,seq(1000,5000,1000))) +
      scale_x_continuous(breaks = seq(-100, 100, 40),
                         limits = c(-80, 65)) +
      facet_grid(data_source ~ era_start) +
      coord_cartesian(expand = 0) +
      labs(title = paste("basin:", unique(.x$basin_AIP)))
  )


```

